### ISSUE TITLE
Add Navbar and remove hover effect

### ISSUE THREAD

**Issue by Ahtaxam** [Resourcio-Community/Resourcio_Community-Website#10]
First in Home page on resources section card should be simple, like we should remove hover effect. 

![Screenshot from 2023-05-20 00-50-56](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/64573767/70dca743-86fd-4cd8-84ad-912739bc372d)

second Navbar should be shown on resources page. 

![Screenshot from 2023-05-20 00-50-42](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/64573767/c72cf99d-2545-4a27-b0d4-27c4802ef77e)

**Note:** I would like to work on this issue. @GSSOC'23

**Comment by rt-001** [comment]
I would like to work on this issue. @GSSOC'23

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by adityavpawar** [comment]
I would like to work on this issue

**Comment by Peacesandy** [comment]
Please assign me this issue as GSSOC 23

**Comment by Abhirup-02** [comment]
Not needed.
