### ISSUE TITLE
unused variables

### ISSUE THREAD

**Issue by Sumit-pd** [Resourcio-Community/Resourcio_Community-Website#100]
## Description

**Describe the bug:**
-run npm start on the terminal
-some unused variables

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots
![Screenshot from 2023-05-24 21-49-59](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/88550925/c8a15115-3e87-4202-a803-a2152b7c120a)

## Additional Information

**Device (please complete the following information):**
- OS:Windows
- Browser : Chrome

**Additional context:**
i would like to work on this issue under gssoc

**Comment by zeitgeistxx** [comment]
It will be used later
