### ISSUE TITLE
[FEATURE REQUEST] Footer section can be updated more

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [Resourcio-Community/Resourcio_Community-Website#103]
## Description

The current footer section is not looking good i.e, UI/UX is not good enough. Also, more content can be added in footer section.

**Solutions**
1.  Social media icon can be bring little bottom side and in centre position.
2.  At right or left side , there should be a form type where review of user can be given or message they want to convey.
3.  UI can be much better and font can be change to have better user experience.

**Screenshots **
<img width="960" alt="image" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/94108574/ddd98b58-0b7a-423e-b4dd-980def4b1a5a">

**Priority** 
The priority level of this feature can be Medium to High.

Please assign me this issue under GSSoC '23 as a contributor.

**Comment by zeitgeistxx** [comment]
You are looking at production deployment. It has been changed.
