### ISSUE TITLE
[STYLE CHANGE] Enhancement of navbar in mobile view.

### ISSUE THREAD

**Issue by abhi03ruchi** [Resourcio-Community/Resourcio_Community-Website#105]
**Description:**
I want to add a smooth transition effect in navbar in mobile view.  

**Reason for Change:** / **Current Styling:**
The hamburger icon doesn't change into the close button on click.
There is no smooth transition effect in the navbar , adding this feature would enhance user experience and engagement.

**Proposed Styling:**

https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/105661636/adb19f3e-ebbc-4495-971f-0bb9c5bf1d20

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

Please assign me this task under gssoc'23.  I am well versed in html, css, javascript and react js.

**Comment by ricardojs122** [comment]
Could you please consider adding the transition property to the navbar selector? It can be implemented like this:
```
.navbar {
  transition-property: background-color;
  transition-duration: 0.3s;
  transition-timing-function: ease;
}
```

**Comment by ricardojs122** [comment]
I took a quick look at the code, but I'm not sure if it will be of much help. LOL

**Comment by zeitgeistxx** [comment]
@abhi03ruchi the first point has been done by somebody else.

You can work on the transition effect.

**Comment by abhi03ruchi** [comment]
ok

**Comment by zeitgeistxx** [comment]
@abhi03ruchi are you working on this?

**Comment by abhi03ruchi** [comment]
yes

**Comment by zeitgeistxx** [comment]
@Abhinavcode13 hey will you work on this?

**Comment by Abhinavcode13** [comment]
Yeah sure , can you just brief about it? @Abhirup-02

**Comment by zeitgeistxx** [comment]
Look at the video above @Abhinavcode13

**Comment by Abhinavcode13** [comment]
@Abhirup-02 how to have mobile view for this website and I can't find the existing navbar ;(

**Comment by zeitgeistxx** [comment]
> @Abhirup-02 how to have mobile view for this website and I can't find the existing navbar ;(

Reduce browser window size. Navbar is in the Components.

**Comment by zeitgeistxx** [comment]
https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/92736753/96882e93-6a3f-40b2-86ed-5c2b73dd41ba

or you can have that doing this

**Comment by Abhinavcode13** [comment]
https://www.loom.com/share/f80a06c3068a47388ca6bc685b6d8650

I found another issue while working with navbar is when navbar comes up , the main logo cropped 25% and I have fixed this can I make a separate issue for this @Abhirup-02

**Comment by zeitgeistxx** [comment]
> https://www.loom.com/share/f80a06c3068a47388ca6bc685b6d8650
> 
> I found another issue while working with navbar is when navbar comes up , the main logo cropped 25% and I have fixed this can I make a separate issue for this @Abhirup-02

Ohhh, that's my bad. I will take care of that..... I did change something on navbar and forgot to fix that.

**Comment by Abhinavcode13** [comment]
I tried adding it , but it didn't work @Abhirup-02 

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/126642111/77e3077e-483f-4826-aa4a-50ca7ff390ee)

**Comment by zeitgeistxx** [comment]
> I tried adding it , but it didn't work @Abhirup-02
> 
> ![image](https://user-images.githubusercontent.com/126642111/243281347-77e3077e-483f-4826-aa4a-50ca7ff390ee.png)

You have to implement animation, transition won't work alone.

**Comment by Abhinavcode13** [comment]
Will work on it afterwards tried a lot past 2hrs lol @Abhirup-02 , tried animations too bro

**Comment by zeitgeistxx** [comment]
> Will work on it afterwards tried a lot past 2hrs lol @Abhirup-02 , tried animations too bro

Keep trying, lol 😄
