### ISSUE TITLE
want to add scroll top button in  "resources /' page 

### ISSUE THREAD

**Issue by gaur15** [Resourcio-Community/Resourcio_Community-Website#106]
## Description

**Is your feature request related to a problem? Please describe.**it becomes easy with scroll up button to reach top fast  and 2nd page resources page doesn't have this feature

**Describe the solution you'd like**

I would like to add scroll top button in 2nd page of website that is"  find resources" 

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by zeitgeistxx** [comment]
@gaur15  keep the button same as the Home page back-to-top button.

**Comment by mandliyarajendra11** [comment]
are you still working on this issue ??  @gaur15  
otherwise you can assign me this issue 
 @Abhirup-02

**Comment by zeitgeistxx** [comment]
If I don't get any response from @gaur15 by this evening, I will assign it to you @mandliyarajendra11. Is that fine?!

**Comment by gaur15** [comment]
> If I don't get any response from @gaur15 by this evening, I will assign it to you @mandliyarajendra11. Is that fine?!

I'm working on this issue sir sorry for being late but this issue will be done today.

**Comment by zeitgeistxx** [comment]
@gaur15  don't call me sir 😄. There's nothing to sorry about. If you are late, just try to keep me updated.

**Comment by mandliyarajendra11** [comment]
> > If I don't get any response from @gaur15 by this evening, I will assign it to you @mandliyarajendra11. Is that fine?!
> 
> I'm working on this issue sir sorry for being late but this issue will be done today.

ok bro ;) .......
