### ISSUE TITLE
Redesigning Resources Page

### ISSUE THREAD

**Issue by prernadabi23** [Resourcio-Community/Resourcio_Community-Website#11]
The resources page lacks visual appeal and appears dull.

1. Add a catchy heading: Introduce a bold and attention-grabbing heading at the top of the resources page. This will make it easier for users to understand the purpose of the page and navigate through the content.
2. Enhance the background color: Replace the plain and uninteresting background color with a more attractive and visually appealing one. Choosing a color scheme that aligns with the overall theme of the website will create a pleasant browsing experience for users.

![Screenshot from 2023-05-20 01-35-33](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/104578155/91994477-4536-4039-a862-d5d2942bfdfa)

**Comment by zeitgeistxx** [comment]
can you send a demo of how the design would look like

**Comment by Avinash905** [comment]
I would like to work on this issue under GSSOC'23

**Comment by prernadabi23** [comment]
I am thinking of something like this which will have a resemblance with the website's other pages. If you want some more changes or any ideas?


![Screenshot from 2023-05-22 13-33-50](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/104578155/56615696-e077-40e4-b1c0-652ab84552de)

@Abhirup-02

**Comment by zeitgeistxx** [comment]
@prernadabi23 heading part is good but keep the cards as it is, also change the background as you see fit. Don't use navbar on resources page. One important thing implement a back button to home page that suits with that heading

**Comment by prernadabi23** [comment]
@Abhirup-02 Okay :)

**Comment by zeitgeistxx** [comment]
@prernadabi23  what's the update from your side
