### ISSUE TITLE
Home Section Element Height

### ISSUE THREAD

**Issue by Praashh** [Resourcio-Community/Resourcio_Community-Website#113]
Home Section element's height looks not good. I think it should be something like that. 

![Screenshot (255)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/99237795/3a25d537-46cf-488a-bd89-7e0105c12a6e)

Hey @Abhirup-02 I am GSSOC contributor Kindly assign this issue to me.

**Comment by Praashh** [comment]
Before Changes:

![Screenshot (256)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/99237795/5f871d94-9cdd-464f-aaf4-0a6d285022ea)

**Comment by Soumyajit2825** [comment]
@Abhirup-02 have a look

**Comment by zeitgeistxx** [comment]
I don't know how this only happens to you. No one faced this before.
