### ISSUE TITLE
Want to add links to the Boxes link[BUG] 

### ISSUE THREAD

**Issue by Kalivarapubindusree** [Resourcio-Community/Resourcio_Community-Website#115]
## Description

**Describe the bug:**
There is no landing page please assign me the work.
![WhatsApp Image 2023-05-26 at 6 18 33 PM](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/114821855/54b9e214-6226-4669-a8b7-eb13b0487d92)

**Expected behavior:**
It will show when we click on hackathons it has to show all the information about hackathons or upcoming hackathons.

**Comment by zeitgeistxx** [comment]
No we are just giving a overview there, of what you can get. It's not a bug.
