### ISSUE TITLE
[FEATURE REQUEST] : ADD Contact Us Form and it's integration with formSubmit

### ISSUE THREAD

**Issue by dev-AshishRanjan** [Resourcio-Community/Resourcio_Community-Website#117]
## Description

**Is your feature request related to a problem? Please describe.**
The problem is if someone wanted to contact your team, they have to use another email services like gmail, outlook etc.

**Describe the solution you'd like**
I wanted to add a form in homepage titled ***Contact us*** and current contact us to be renamed ***out team***.
In contact us form we take some inputs : 
- name
- email
- message

After someone fills this form and click submit button the email is sent directly to your official email

## Additional Information

**Context**
For reference you can visit - https://www.krashish.live/contact

**Potential Implementation** (optional)

**Screenshots or Mockups** (optional)

**Priority** (optional)
*Medium*

**Additional Notes** (optional)

**Comment by dev-AshishRanjan** [comment]
I have provided a detailed solution and have implemented the solution myself - https://www.krashish.live/contact

So, if you can assign this to me (under GSSoC'23) I can start working for this site too.

**Comment by zeitgeistxx** [comment]
We have already given that in footer section.
