### ISSUE TITLE
[STYLE CHANGE]Enhancing the Design of Footer

### ISSUE THREAD

**Issue by Vishalk91-4** [Resourcio-Community/Resourcio_Community-Website#120]
**Description:**

We can add many verticals like Resource Page, Company Page and Social Page, FAQ section to be created with it's link here in Footer with Company's Logo and a Tagline Below
A copyright Sign Below

@Abhirup-02 can you please assign this to me under GSSOC23

**Reason for Change:**

[Explain the reasons behind the requested style change, such as usability, branding, or user experience.]

**Current Styling:**

[Describe the current styling that needs to be changed.]

**Proposed Styling:**

[Describe the desired styling or changes you would like to see.]

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by Abhirup-02** [comment]
Assigned to somebody else
