### ISSUE TITLE
[STYLE CHANGE] Imroving the Design of the Front Page

### ISSUE THREAD

**Issue by Vishalk91-4** [Resourcio-Community/Resourcio_Community-Website#121]
**Description:**

The Navbar and the Page below it has a lot of void space in it, so we can add Girl Script in a better form with some Design so that there are less spaces and improving the Navbar with it so that the Light/Dark mode can fit in it and it looks nice with the colour scheme.

**Reason for Change:**

[Explain the reasons behind the requested style change, such as usability, branding, or user experience.]

**Current Styling:**

[Describe the current styling that needs to be changed.]

**Proposed Styling:**

[Describe the desired styling or changes you would like to see.]

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by zeitgeistxx** [comment]
Not needed.
