### ISSUE TITLE
[BUG] All columns are not properly aligned in Resources section

### ISSUE THREAD

**Issue by Vishalk91-4** [Resourcio-Community/Resourcio_Community-Website#122]
## Description

**Describe the bug:**
I f the devices are changed, we find that the 4 columns of resources, are not of the same height.

**Expected behavior:**

**Actual behavior:**
Laptop
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/116670999/01a04f26-763d-4b73-801a-309cd19c1f41)

Tablet
![Screenshot 2023-05-27 143259](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/116670999/2ddc1826-6fc9-4492-b2dd-b5193aeebf99)

@Abhirup-02 can you please assign this to me under GSSOC23

## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

**Comment by Abhirup-02** [comment]
It's fixed not deployed to production. Look at the announcement is issues properly.
