### ISSUE TITLE
[STYLE CHANGE] Request a change in style of Resource Card Design  [level 2]

### ISSUE THREAD

**Issue by Sattwikmaiti** [Resourcio-Community/Resourcio_Community-Website#124]
**Requesting a change in Style of Resource Card Design** 
[level 2]
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/90182231/dddcde4b-4b68-4e46-ac07-18fdd5726f40)

**Comment by Abhirup-02** [comment]
not required.
