### ISSUE TITLE
[STYLE CHANGE] Resources Page Background style and Card style can be improved heavily

### ISSUE THREAD

**Issue by itsme-shivamkumar** [Resourcio-Community/Resourcio_Community-Website#128]
## Description:

Background of Resources page can be improved and card's layout and designing can be improved too!

## Current Styling:

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/91745441/28775758-8717-4364-8616-00fd9014a901)

## Proposed Styling:

We can make the website look more vibrant as per the feel and the theme of the whole website.

### For background I can use linear-gradient with animation
e.g. 
![bgdemo](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/91745441/4fff6ad9-e081-40ca-a33c-ae1779628367)
NOTE: [I have implemented this bg on my personal project]

### Before: 
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/91745441/5598dfc7-b272-4eb0-a5a5-3cfd53927ecc)

### After:
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/91745441/c5398c16-ecc6-420b-bb6a-26bd4188834b)

## Priority Level (optional):

- [ ] Low
- [x] Medium
- [ ] High

## Being a participant of GSSOC 23, I would love to contribute to this project, Kindly assign it to me, with my current knowledge of HTML, CSS, Javascript, React, and Backend Skills, I think, I can bring a fruitful value to this project. Thank You.

**Comment by Sattwikmaiti** [comment]
How is this style ?
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/90182231/4f7b75b4-9f94-4c4a-bd98-80402fae5288)

**Comment by Rishav1707** [comment]
What do you think about this for the resource page? @Abhirup-02 

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/97666287/04c60cba-7126-4894-af2b-a144802dc30f)

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/97666287/55dd83d8-7f7b-445e-ae0b-656011fd139b)

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/97666287/bba85ee0-9882-4bae-ad1c-d8989d73f1b2)

## OR this - 

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/97666287/942b758e-a2cf-4bc1-8ec8-3c1546b9c0ba)

**Comment by zeitgeistxx** [comment]
Not required.
