### ISSUE TITLE
[BUG] The top nav bar not visible once page is scrolled down.

### ISSUE THREAD

**Issue by raaksss** [Resourcio-Community/Resourcio_Community-Website#129]
## Description

**Describe the bug:**
As soon as we scroll the page, the navbar disappears. 

**Expected behavior:**
Even if we scrolled up and forth the page, the navbar should be visible at all times for easy navigation from one section to the other.

**Expected result:**
A navbar that would be displayed to the user at all times.

## Screenshots
![Screenshot 2023-05-28 132640](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/102184647/236ffb9e-8ecb-4f22-8315-b60e67b9945f)

As it can be clearly seen that the navbar isn't visible right now. If the user wishes to go to any other section, he would have to go to the top of the page and then select another category to visit.

**Device (please complete the following information):**
- OS: Windows
- Browser Chrome

**Comment by raaksss** [comment]
Hi, pls assign me this issue under GSSoC'23!

**Comment by zeitgeistxx** [comment]
Please look at the preview of the website. You are not seeing the latest changes.
