### ISSUE TITLE
Improve the footer for the project GSSOC'23

### ISSUE THREAD

**Issue by karthiknadar1204** [Resourcio-Community/Resourcio_Community-Website#13]

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by mishba-ai** [comment]
can you assign this issue to me under gssoc'23?

**Comment by karthiknadar1204** [comment]
The logo to the top left of the footer,he sweet message below the logo
Reduce the height of the footer as it is unnecessarily tall,Adding the whatsapp and mail options to the right and the social icons to the left with some more engaging hover effect
My proposed solution

**Comment by utkars3** [comment]
As you have mentioned to reduce the height and adding whatsapp and mails options with some more engaging hover effect. I will do it as I have already worked on this type of things in react.You can see my portfolio website too at https://utkars3.github.io/BIO. Therefore I request you to please assign this issue to me so that I acn solve it.
And also please add the tag gssoc 23

**Comment by karthiknadar1204** [comment]
@utkars3 I am waiting for it to be assigned to me

**Comment by An525ish** [comment]
![foot](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/93612051/0367ff94-c99e-481b-b5c7-5d89edfef3ef)
![footer](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/93612051/1393381b-c1f0-4b24-8afb-8f4f936752cc)
I have already made some layout changes for the footer to make it look better and created a PR...can you please review it once

One more suggestion : It will look better if we just remove that white background of the logo...let me know if I can do that

**Comment by karthiknadar1204** [comment]
@An525ish Please wait for the issue to be assigned first, it is the basic courtesy in open source to wait for the issue to be assigned first ,I created the issue and have been waiting patiently for the issue to get assigned as well.
Randomly opening a pr for a issue everyone is patiently waiting for to get assigned is an insult to everyone .
Please refrain from doing this because if everyone indulges in this practice, it would be nothing but chaos.

**Comment by An525ish** [comment]
> use if everyone indulges in this practice, it would be nothing but chaos.

Hey, I am so sorry...even I thought of the same but when I saw other people doing that and as project admin wasn't replying to any of that than I felt like I should be doing the same to get it assigned...so sorry for this

**Comment by karthiknadar1204** [comment]
Its fine,even i saw many people doing the same, we should refrain from doing the same though,the admins have slowly started assigning the issues

**Comment by zeitgeistxx** [comment]
@karthiknadar1204  can you describe how the footer would look like after the change. And wait for the issue to be assigned, I haven't got the official issue tags yet, so be patient.

**Comment by karthiknadar1204** [comment]
The logo to the top left of the footer, the sweet message below the logo
Reduce the height of the footer as it is unnecessarily tall,Adding the whatsapp and mail options and the social icons to the right with some more engaging hover effect
My proposed solution

How does it sound @Abhirup-02

**Comment by zeitgeistxx** [comment]
I will tell the final design by today, hold on a bit.

**Comment by karthiknadar1204** [comment]
Fine

**Comment by zeitgeistxx** [comment]
@karthiknadar1204 can you show me how the footer would  look like  after your recommended changes.

**Comment by karthiknadar1204** [comment]
I'll share a design template by tomorrow evening

**Comment by karthiknadar1204** [comment]
> The logo to the top left of the footer, the sweet message below the logo Reduce the height of the footer as it is unnecessarily tall,Adding the whatsapp and mail options and the social icons to the right with some more engaging hover effect My proposed solution
> 
> How does it sound @Abhirup-02

I think i'll stick to this template,Do you have any specific design for the footer that you want me to implement @Abhirup-02

**Comment by zeitgeistxx** [comment]
@karthiknadar1204 do what you proposed, just don't take Whatsapp and mail to the right, keep them where they are

**Comment by karthiknadar1204** [comment]
Fine will do it

**Comment by karthiknadar1204** [comment]
Will try setting up the project in sometime,will ping in the channel in ade in any issue arises

**Comment by karthiknadar1204** [comment]
I'll work it out in a responsive frame as well,that would sum up the issue precisely
THANK YOU

**Comment by karthiknadar1204** [comment]
Have begun the work @Abhirup-02 ,WIll try to submit pr for review by day after tomorrow

**Comment by karthiknadar1204** [comment]
<img width="1779" alt="Screenshot 2023-05-24 at 8 31 11 PM" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/95973644/31d7c934-5bd6-43e3-b6d1-68cd83b91815">

The newly designed navbar
Reduced the size of the footer overall,
Did not budge the mail and whatsapp icon as you wanted.
Moved the social links to make a better alignment and reduced the size of the logo.
Des this design work @Abhirup-02

**Comment by karthiknadar1204** [comment]
<img width="1792" alt="Screenshot 2023-05-24 at 8 34 54 PM" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/95973644/5dc76ef2-0200-447c-90c1-078e0586c769">
Working on the bug to get rid of the small white space below, once done, will submit pr for review.

**Comment by karthiknadar1204** [comment]
Please share any possible improvement you might want in the project

**Comment by zeitgeistxx** [comment]
Keep the copyright close to bottom. 
Keep whatsapp and mail aligned with the logo and the text. @karthiknadar1204

**Comment by karthiknadar1204** [comment]
Ok will align the whatsapp and mail icon and will use the white space for the copyright statement
Will get to it right away @Abhirup-02

**Comment by karthiknadar1204** [comment]
<img width="1792" alt="Screenshot 2023-05-24 at 8 45 23 PM" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/95973644/30bb7ef2-d7c7-4ebe-9632-53308ddb87ed">

Check this out @Abhirup-02

**Comment by karthiknadar1204** [comment]
I tried reducing the height of the navbar but it is working against the cause, Should i include the copyright message in the black footer or is this fine

**Comment by zeitgeistxx** [comment]
> I tried reducing the height of the navbar but it is working against the cause, Should i include the copyright message in the black footer or is this fine

In the footer.

**Comment by karthiknadar1204** [comment]
okie, will do

**Comment by zeitgeistxx** [comment]
The whole black footer should stick to the bottom

**Comment by karthiknadar1204** [comment]
Yes, on it

**Comment by karthiknadar1204** [comment]
Adding some hover effect to the social icons such that they turn to their original icon colors when hovered,Will share preview in some time

**Comment by karthiknadar1204** [comment]
<img width="1774" alt="Screenshot 2023-05-24 at 9 23 05 PM" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/95973644/e067d257-47e2-42bd-8ad0-d19b99860458">

@Abhirup-02 How does this look

**Comment by zeitgeistxx** [comment]
Why does the footer look taller than before!!

**Comment by karthiknadar1204** [comment]
<img width="1789" alt="Screenshot 2023-05-24 at 9 26 14 PM" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/95973644/e21b7ef1-cb94-4715-bd58-07aff37ad324">

Pushed the line slightly above to makr a proper demarkation

**Comment by zeitgeistxx** [comment]
ok demarkation looks good. But the footer is too tall

**Comment by karthiknadar1204** [comment]
The excess black space was not looking right so added the demarkation line

**Comment by karthiknadar1204** [comment]
And for the height issue, looking into it

**Comment by zeitgeistxx** [comment]
> And for the height issue, looking into it

Yeah that's the only issue left and are you making it responsive?

**Comment by karthiknadar1204** [comment]
yes, will share the responsive layout as well in a bit

**Comment by karthiknadar1204** [comment]
I haven't fiddled with css for adjusting the height of the footer, just changed the alignment of the elements inside the footer.
Dont know why is the footer bigger, looking it up

**Comment by zeitgeistxx** [comment]
Adjust whatever is necessary I will review your PR if there's anything to change I will tell you. So don't worry

**Comment by zeitgeistxx** [comment]
Preview will be available to me before merging, so no worries.

**Comment by karthiknadar1204** [comment]
Thank you

**Comment by karthiknadar1204** [comment]
@Abhirup-02 Worked out the height issue, had two additional containers so was increasing the height,As for the responsiveness, will raise a separate issue for the same as it doesn't seem to be working at all, might have to pry deeper into it. Have added a few more last moment designs, hope you like it
<img width="1784" alt="Screenshot 2023-05-24 at 9 53 38 PM" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/95973644/9cd882d9-b413-4f9c-847c-470317c35641">

**Comment by karthiknadar1204** [comment]
i'll submit a pr for review @Abhirup-02

**Comment by zeitgeistxx** [comment]
The new logos don't look good. Keep the previous ones, tweak with hover animation

**Comment by karthiknadar1204** [comment]
ok

**Comment by karthiknadar1204** [comment]
@Abhirup-02 Have submitted pr for review

**Comment by zeitgeistxx** [comment]
@karthiknadar1204 footer is messing  up the whole UI. When changing window size

**Comment by karthiknadar1204** [comment]
Will open up a separate issue for responsiveness of the footer ,does that work?

**Comment by karthiknadar1204** [comment]
@Abhirup-02

**Comment by zeitgeistxx** [comment]
Work under this issue

**Comment by zeitgeistxx** [comment]
I reverted the PR

**Comment by karthiknadar1204** [comment]
Will check in my local system and get back to you again tomorrow

**Comment by karthiknadar1204** [comment]
@Abhirup-02 Have begun the work again on this issue, could you elaborate what all issues occurred , will write the code accordingly. I think the design works just fine.
How did the footer disrupt the ui

**Comment by karthiknadar1204** [comment]
@Abhirup-02 Will try to resolve it by weekend
Thank you for your patience

**Comment by zeitgeistxx** [comment]
I will not be more attainable till 15th June due to endsem exams. Sorry for the inconvenience

**Comment by karthiknadar1204** [comment]
its fine, even my exams are going on so was running behind on a few issue, thats why was updating.
Whom can i tag for any further assistance though

**Comment by zeitgeistxx** [comment]
You just have to wait in these case. Everyone is having exams right now. It wouldn't be a issue in reviewing PRs, but interacting may not be possible.

**Comment by karthiknadar1204** [comment]
Ah its fine, Can wait
Thank you though
All the best

**Comment by karthiknadar1204** [comment]
Exams over, will clear this issue tomorrow

**Comment by karthiknadar1204** [comment]
@Abhirup-02 Done with the responsiveness as well, will submit pr for review today evening

**Comment by karantec** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
@Abhirup-02 Share your screen size, will render the components accordingly and wrap up this issue

**Comment by zeitgeistxx** [comment]
1920x1080

**Comment by swayamshreenanda20** [comment]
Hi,
I would like to work on this issue under gssoc'23
Can you assign it to me?

**Comment by Naina047** [comment]
I'm a GSSOC'23 contributor.  I would like to work on this issue, Please assign me this issue.

My proposed solution:
footer is actually very big, it's size should be reduced by -
Logo should be big and to the left. All other thankyou message and social media should be on the right of logo.

**Comment by zeitgeistxx** [comment]
It has been opened for too long, closing this issue.
