### ISSUE TITLE
[FEATURE REQUEST]  Sitemap For SEO

### ISSUE THREAD

**Issue by krishnamangal98** [Resourcio-Community/Resourcio_Community-Website#130]
## Description

**Is your feature request related to a problem? Please describe. Sitemap addition for SEO
A clear and concise description of the problem or limitation that the requested feature would address.

**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by zeitgeistxx** [comment]
Hey @krishnamangal98  sorry for inconvenience. Are you still willing to work on this issue?

**Comment by krishnamangal98** [comment]
Sure, I can do that. @Abhirup-02

**Comment by zeitgeistxx** [comment]
Ok great.
