### ISSUE TITLE
Resources page color theme [STYLE CHANGE]

### ISSUE THREAD

**Issue by Once-kaur** [Resourcio-Community/Resourcio_Community-Website#136]
**Description:**
I want to work on the current style of the resources page and its color theme 

**Reason for Change:**
The current  color theme  of the resources page doesn't match with rest of the website

**Current Styling:**
the current color scheme seems dull compared to the subtle light color theme of the rest of the website
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/95931242/f18c378e-dd0e-40ba-a53f-945322dffc86)

**Comment by zeitgeistxx** [comment]
it's already changed.
