### ISSUE TITLE
Add Readme 

### ISSUE THREAD

**Issue by mishba-ai** [Resourcio-Community/Resourcio_Community-Website#14]
Readme should contain:
 the description of the project
Installation Instruction
Usage Guide
License
Contact Information-Provide a way for users to contact the project maintainers

**Comment by mishba-ai** [comment]
I want to work on this assign. can you plz assign this issue to me under GSSOC'23?

**Comment by AMAN-J-B** [comment]
> Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
> I will try to make it as different as possible and exciting also.
> Please assign it to me. Thank you in advance.

**Comment by mishba-ai** [comment]
plz assign this issue to me , I have opened this issue

**Comment by zeitgeistxx** [comment]
Already someone is working on this.
