### ISSUE TITLE
[DOCS] Add Contributors Graph

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [Resourcio-Community/Resourcio_Community-Website#140]
* I would like to incorporate a contributor graph in the README.md file as a means of acknowledging and appreciating the work of contributors. I kindly request to be assigned this particular issue.
* Here is an example of the work I aspire to undertake within this project.

![Screenshot (80)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/112751524/1ae87b7c-6e1a-433d-9980-2bc014951466)

**Comment by zeitgeistxx** [comment]
Not needed.
