### ISSUE TITLE
Add Google Authentication for Login and Register. {GSSoC '23}

### ISSUE THREAD

**Issue by youraj-08** [Resourcio-Community/Resourcio_Community-Website#148]
## Description

**Is your feature request related to a problem? Please describe.**
1) It simplifies the registration process by allowing users to sign up using their existing Google accounts, eliminating the need for a new account and reducing the registration steps. 
2) It enhances security by leveraging Google's robust security measures, reducing the risk of unauthorized access or data breaches. 
3) It increases user trust as many users are familiar with and trust Google's authentication services.

**Describe the solution you'd like**
The feature entails enabling users to authenticate using their Google account with the assistance of Auth0. By implementing this functionality, we can enhance the user experience and provide a seamless onboarding process.

**Describe alternatives you've considered**
Alternatives include authentication through other popular social media platforms like Facebook or Twitter, giving users a choice of platforms for logging in.

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by zeitgeistxx** [comment]
not required now.
