### ISSUE TITLE
Improving Landing Page in terms of Margin, Spacing and designs [GSSOC ' 23]

### ISSUE THREAD

**Issue by CodeMaster17** [Resourcio-Community/Resourcio_Community-Website#15]
I would love to improve the landing page of this website in terms of Margin, Spacing, Fonts, Boxes etc. I went through your website and found number of design errors

1. Navbar is too big
2. Text in home screen is not taking enough space
3. Boxes made are not elegant
4. Font Size is not good etc

Allow me to work under GSSOC'23

**Comment by Peacesandy** [comment]
Please assign me this issue as GSSOC 23

**Comment by zeitgeistxx** [comment]
The website follows minimalistic design. So I think no other changes required in case of styling.
