### ISSUE TITLE
Ui of the resources page.

### ISSUE THREAD

**Issue by Pragati-3003** [Resourcio-Community/Resourcio_Community-Website#151]
I would like to change the ui of the resources page .
![Screenshot 2023-05-31 155750](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/132778037/483847aa-cb5c-4dbb-b570-e6d4db1938e7)
I would like to change the cards of the page by adding cool box shadows and hover effects.
So,please assign this to me under GSSOC'23.

**Comment by zeitgeistxx** [comment]
NOT Needed.
