### ISSUE TITLE
[FEATURE REQUEST] Adding search bar in resources

### ISSUE THREAD

**Issue by Dimple-Choudhary** [Resourcio-Community/Resourcio_Community-Website#152]
## Description

**Is your feature request related to a problem? Please describe.**
The current resources page lacks a search functionality, making it difficult for users to find specific resources efficiently.

**Describe the solution you'd like**
I would like to add a search bar feature implemented on the resources page. This search bar should allow users to enter keywords or phrases related to the resources they are looking for. Upon entering a search query, the page should display a list of relevant resources based on the search terms.
**Describe alternatives you've considered**
One alternative solution would be to organize the resources into different categories or tags and provide navigation links to each category. However, this approach may not be as flexible or efficient as a search bar when dealing with a large number of resources.

## Additional Information

**Context**
The Resource website aims to provide various resources for Users. The current resources page lists all the available resources in a linear format without any search functionality.
**Potential Implementation** (optional)
To implement the search bar feature, the following steps can be considered:

-Design and add a search bar element to the resources page.
-Implement a search function that takes the user's input and matches it against the resource titles or descriptions.-
-Display the search results on the page in a separate section or by filtering the existing resource list.

**Screenshots or Mockups** (optional)
![Untitled (1)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/96401557/f1bce781-4cc3-43b8-afbc-01b4a3a03cc3)

**Additional Notes** (optional)
@Abhirup-02, will you assign me this issue under GSSoC'23

**Comment by zeitgeistxx** [comment]
Great idea.

**Comment by Abhinavcode13** [comment]
@Dimple-Choudhary what's the update?

**Comment by Dimple-Choudhary** [comment]
sorry! I won't be able to do that because I am not familiar with the backend  yet .

**Comment by Abhinavcode13** [comment]
@Abhirup-02 what about this?

**Comment by Abhinavcode13** [comment]
> sorry! I won't be able to do that because I am not familiar with the backend yet .

All okay @Dimple-Choudhary :)

**Comment by zeitgeistxx** [comment]
There's nothing to do with backend, all the resources' title are static in frontend.

**Comment by zeitgeistxx** [comment]
@Abhinavcode13 are you gonna take this issue, if you face any problem doing it I can help. And help you in refactoring the resources to implement the search.

**Comment by Abhinavcode13** [comment]
Yeah sure @Abhirup-02

**Comment by zeitgeistxx** [comment]
Okay @Abhinavcode13 lets not talk about it here. I have started a discussion about it in Discussions, so go check it out

**Comment by harmeetsingh11** [comment]
Hi, anyone working on this issue? Can I work on this issue under GSSoC'23? @Abhirup-02

**Comment by zeitgeistxx** [comment]
Yes working.

**Comment by Abhinavcode13** [comment]
hey @Abhirup-02 where is the resource component?
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/126642111/7f401bc9-66cc-42bc-8d33-720ee438e853)

**Comment by zeitgeistxx** [comment]
Within scenes directory

**Comment by zeitgeistxx** [comment]
Hey @Abhinavcode13  continue in discussions, whatever you need to know

**Comment by Abhinavcode13** [comment]
Ok cool @Abhirup-02

**Comment by zeitgeistxx** [comment]
> Okay @Abhinavcode13 lets not talk about it here. I have started a discussion about it in Discussions, so go check it out

@Abhinavcode13

**Comment by mandliyarajendra11** [comment]
@Abhinavcode13  are you still working on this issue ?
@Abhirup-02   i can solve this issue with debouncing concept
 can you assign me this issue

**Comment by komalioruganti** [comment]
Can you assign me this issue? I am familiar with how it should be done. If you assign me this I will start working.
