### ISSUE TITLE
[STYLE CHANGE] Logo in Footer should have transparent background for better look without border

### ISSUE THREAD

**Issue by ManasMadan** [Resourcio-Community/Resourcio_Community-Website#154]
**Description:**
The Logo in Footer should have transparent background for better look.

**Reason for Change:**
The deign change enhances the UI

**Current Styling:**
<img width="648" alt="image" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/84731321/75ecb798-eb21-44b5-b70c-d0ea604f5eb7">

**Proposed Styling:**
<img width="667" alt="image" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/84731321/fba606f4-e24a-4c81-8c77-8da6ccf6dbed">

**Priority Level (optional):**

- [ ] Low
- [X] Medium
- [ ] High

**Timeline (optional):**
Will Do it in 1 day

**Possible Implementation Approach (optional):**
- I will be using Pure CSS no library.
- Image will not be changed

**Comment by ManasMadan** [comment]
@Abhirup-02 Please assign me this issue under GSSoC 23

**Comment by zeitgeistxx** [comment]
Already someone is working on footer designing.
