### ISSUE TITLE
Add Contributor's in your Readme 

### ISSUE THREAD

**Issue by apoorvaron** [Resourcio-Community/Resourcio_Community-Website#157]
## Description

**Is your feature request related to a problem? Please describe.**
Add Contributor's in your Readme will motivate Students to contribute more in your project. 

**Describe the solution you'd like**
I will Add dynamic number of contributors in your Readme file.

**Describe alternatives you've considered**
It is the easiest method

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
Just add link to dynamic contributors

**Screenshots or Mockups** (optional)
It is most common feature which is just missed by chance.

**Priority** (optional)
Priority could be low to mid. 

**Additional Notes** (optional)
No

I am GSSOC contributor as well as Project Admin , Can you please assign this to me ?
If you assign this to me , Please add labels 

Thanks , 
Apoorv Aron

**Comment by zeitgeistxx** [comment]
No need for that.
