### ISSUE TITLE
[Bug] - SignUp page - Input has space issue

### ISSUE THREAD

**Issue by ApurvaZun** [Resourcio-Community/Resourcio_Community-Website#158]
## Description

**Describe the bug:**
On SignUp page, While typing you can't give space in Name.

**Expected behavior:**
While typing in Name input, you should be able to give space.

**Actual behavior:**
A clear and concise description of what actually happened.

## Reproduction Steps

**Steps to reproduce the behavior:**
1. Go to SignUp
2. Type in Name input box.
3. Try to type Lorum ipsum.

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

**Comment by zeitgeistxx** [comment]
it has been fixed, not deployed to production yet
