### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by ApurvaZun** [Resourcio-Community/Resourcio_Community-Website#159]
## Description

After User Login and lands on the HomePage, show the name of the user on the right side and on the hover of the name, give option to logout.

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/57218798/a672efa6-3409-4846-ad4d-a073eb119e45)

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by zeitgeistxx** [comment]
That's a great idea, the thing is right now you don't have access to name.

I have changed the API for that but it is not deployed to production. I am assigning you to this issue, and when the API will be updated I will inform you and you can start your work.

**Comment by zeitgeistxx** [comment]
@ApurvaZun I have updated the API, now you can carry on.

**Comment by ApurvaZun** [comment]
Thanks!

**Comment by sshiwangi** [comment]
Hey @Abhirup-02, If it's not done yet, can I work on this issue under gssoc'23

**Comment by zeitgeistxx** [comment]
@ApurvaZun  what's your progress?

**Comment by zeitgeistxx** [comment]
hey @sshiwangi i have got no response from the assignee.

You can work on it.

**Comment by zeitgeistxx** [comment]
No settings option will be needed.

**Comment by sshiwangi** [comment]
> No settings option will be needed.

Got it! Will complete it ASAP.

**Comment by zeitgeistxx** [comment]
@sshiwangi  hey what's your update?

**Comment by sshiwangi** [comment]
> @sshiwangi hey what's your update?

I went to a hackathon sorry. I will push it today, it's almost done.

**Comment by zeitgeistxx** [comment]
> > @sshiwangi hey what's your update?
> 
> I went to a hackathon sorry. I will push it today, it's almost done.

Lol, same from my side too.

**Comment by sshiwangi** [comment]
> > > @sshiwangi hey what's your update?
> > 
> > 
> > I went to a hackathon sorry. I will push it today, it's almost done.
> 
> Lol, same from my side too.

Hey, I updated the code, but I encountered a problem. I am unable to register or log in when working locally, but it works perfectly fine on the hosted website. However, if I am unable to see the results of my code locally, how can I push it?

**Comment by zeitgeistxx** [comment]
@sshiwangi have you added the API endpoint to frontend in env file?

**Comment by sshiwangi** [comment]
> @sshiwangi have you added the API endpoint to frontend in env file?

I forgot to do that 😅. Will check it and make a pr. Thank you so much:)

**Comment by sshiwangi** [comment]
> @sshiwangi have you added the API endpoint to frontend in env file?

Created the pr, please check.
