### ISSUE TITLE
Proper Documentation - Adding ReadMe File [GSSOC ' 23]

### ISSUE THREAD

**Issue by SamPrinceFranklin** [Resourcio-Community/Resourcio_Community-Website#16]
**_Issue Description:_**

> We need to update the project's Readme file to provide essential information for users. The Readme should include the following sections:

**Project Description:**
Provide a clear and concise description of the project, explaining its purpose, features, and any relevant background information.

**Installation Instructions:**
Detail the steps required to install and set up the project. Include any dependencies or system requirements that users should be aware of.

**Usage Guide:**
Provide a comprehensive guide on how to use the project. Include examples, code snippets, and any relevant instructions to help users understand and utilize the project effectively.

**License:**
Clearly specify the license under which the project is distributed. Ensure that it aligns with the project's open-source or proprietary nature, and provide any necessary attributions or disclaimers.

**Contact Information:**
Include a section that allows users to easily contact the project maintainers. Provide relevant contact details such as email addresses, social media handles, or links to communication channels (e.g., Slack, Discord) where users can seek assistance or report issues.

> I am ready to take up this and provide an detailed documentation for this project. Please assign me for this :)

**Comment by zeitgeistxx** [comment]
Already someone is working on this.
