### ISSUE TITLE
[STYLE CHANGE] Stats

### ISSUE THREAD

**Issue by Harshu467** [Resourcio-Community/Resourcio_Community-Website#160]
**Description:**

[Provide a clear and concise description of the style change you are requesting.]

Above Contact us page there are cards with numbers and we can add design so that it could change dynamically from zero to that particular number. Like 1000 will be shown as 0 to 1000 for particular time where numbers will be added

**Reason for Change:**

[Explain the reasons behind the requested style change, such as usability, branding, or user experience.]

Most of user friendly website has this feature which attracts users. It is better and user friendly 

**Current Styling:**

[Describe the current styling that needs to be changed.]

Current Design is just card with some numbers which does not look good.

**Proposed Styling:**

[Describe the desired styling or changes you would like to see.]

Can Change it to dynamic numbering which is user friendly

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

![Screenshot from 2023-06-03 16-28-17](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/89975347/6293d697-eb12-46d6-807e-845dae17ee72)

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [x] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by Harshu467** [comment]
Assign it to me

**Comment by zeitgeistxx** [comment]
@Harshu467  Counter is already there, it starts as soon as the page loads. 

If you can make that counter starts, when a user goes to that section, it would be great.
