### ISSUE TITLE
[STYLE CHANGE] The Events Part can be improved

### ISSUE THREAD

**Issue by ManasMadan** [Resourcio-Community/Resourcio_Community-Website#161]
**Description:**
This section as shown in the Screenshot can be improved by adding GSSoC Logo so it takes full height

**Reason for Change:**
Addition of Images can enhance UX

**Current Styling:**
Empty Space Should Be Utilized

**Proposed Styling:**
Add A Image to take up the space

**Screenshots or Design Mockups (optional):**
<img width="237" alt="image" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/84731321/1d44f707-dc4b-4c74-a408-95544043fd32">

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [X] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**
Add GSSoC Logo

**Comment by ManasMadan** [comment]
@Abhirup-02 assign me this issue under GSSoC 23

**Comment by zeitgeistxx** [comment]
Not necessary.
