### ISSUE TITLE
[STYLE CHANGE] The Sign In Link Should have a background color

### ISSUE THREAD

**Issue by ManasMadan** [Resourcio-Community/Resourcio_Community-Website#162]
**Description:**
The Sign in link on the navbar should have a background.

**Reason for Change:**
Having a background on the link can attract user attention leading to more user sign in

**Current Styling:**
The Link Looks merged

**Proposed Styling:**
The Link will pop out because of a background color

**Screenshots or Design Mockups (optional):**
<img width="384" alt="image" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/84731321/1eb87cad-c753-4c1f-9c1a-7154244ace4f">

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [X] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by ManasMadan** [comment]
@Abhirup-02 Please assign me this under GSSoC 23

**Comment by zeitgeistxx** [comment]
Not required.
