### ISSUE TITLE
Missing Pull Request template

### ISSUE THREAD

**Issue by DivyanshiNarang** [Resourcio-Community/Resourcio_Community-Website#165]
Pull Request Template means when someone opens a Pull Request, they will have a template that they can edit making it easier for maintainers of the project to review PR and make sure that no PR is submitted without proper description.

Please assign this issue to me under GSSoC'23
@Abhirup-02

**Comment by zeitgeistxx** [comment]
@DivyanshiNarang thanks for noticing that.

**Comment by zeitgeistxx** [comment]
hey @DivyanshiNarang will you add the template?

**Comment by DivyanshiNarang** [comment]
Hello @Abhirup-02, sure I'll add the template. Sorry for the delay.
