### ISSUE TITLE
Change style of badges in ReadMe.md

### ISSUE THREAD

**Issue by VSatwika** [Resourcio-Community/Resourcio_Community-Website#168]
- I would like to improve the overall look of the ReadMe.md file by changing the existing badges to better ones.
 - The badges I want to include will look like the ones in the attached picture.
 - I would like to work on this. Could this issue be assigned to me under GSSoC'23?

  
<img width="625" alt="badges" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/112561024/b260d7f6-9344-4466-9b7d-36beb1e43da2">

**Comment by zeitgeistxx** [comment]
No need for that.
