### ISSUE TITLE
Fix Image Size for Team Members [GSSOC ' 23]

### ISSUE THREAD

**Issue by SamPrinceFranklin** [Resourcio-Community/Resourcio_Community-Website#17]
### **_Issue Description:_**

> The current images of the team members on the project website are not fitting properly within their respective sections. We need to fix the image sizes to ensure a consistent and visually appealing display.

### Issue Details:

**Image Dimensions:**
Review the dimensions of the team member images and ensure that they are consistent in size. This will create a more uniform and professional appearance across the website.

**Aspect Ratio:**
Verify that the aspect ratio of the images is maintained during resizing. Stretching or distorting the images can negatively impact the visual quality and make team members appear distorted or disproportionate.

**Responsive Design:**
Ensure that the images are responsive and adjust appropriately based on different screen sizes. This will guarantee that team member images look good on various devices, including desktops, tablets, and mobile phones.

**CSS/HTML Adjustments:**
Make any necessary CSS or HTML modifications to accommodate the desired image sizes. Review the relevant stylesheets and HTML templates to ensure that the images are displayed optimally.

_I am ready to work on this issue and solve them! Please assign me to this_

**Comment by venkataraviraja5** [comment]
I am GSSOC contributor i want to work on this issue please assign to me

**Comment by zeitgeistxx** [comment]
No changes required in images in team members section.
