### ISSUE TITLE
[STYLE CHANGE] Improve Footer in smaller devices

### ISSUE THREAD

**Issue by Ayush9951** [Resourcio-Community/Resourcio_Community-Website#173]
Hi, I am a contributor in GSSoC'23.
Footer Card is not responsive in smaller devices.
I want to work on Fixing this issue.
I will make the content center align and Add Media Queries to Improve Responsiveness.
please assign me this task under label gssoc'23

![Screenshot 2023-06-05 140345](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/60573378/cc77e4d8-4833-4fc5-9113-3dd1576915be)

**Comment by zeitgeistxx** [comment]
Somebody is already working on footer.
