### ISSUE TITLE
Rethinking the validation on name and username

### ISSUE THREAD

**Issue by mukul314** [Resourcio-Community/Resourcio_Community-Website#177]
While using the website  I noticed that, there were validations on name and username too. I guess this should be left to the users so that they can decide what usernames they want to choose and how long they should be. We can surely put an upper limit but the lower limit should be kept in the hands of the users (Ofcourse the name must not be blank ). Also there is a validation on the name part that it must be six characters long, in my case my name is MUKUL, which is 5 characters long so either the placeholder should ask for the full name or the validation must be removed.

<img width="401" alt="2023-06-05 20_11_12-Sign in - Brave" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/76463001/0cd99d7f-5cb1-4c61-81c8-377bb779f26f">

Also I wanted to add the signup functionality with google, this will make the website's interaction more smooth with the user.

What are your thoughts about it @Abhirup-02 ?

**Comment by zeitgeistxx** [comment]
Name will be your full name, have you seen anywhere where user gives only his first name!!!!!

And username should be descriptive, but it can cut down to 6 characters.
