### ISSUE TITLE
[FEATURE REQUEST] Adding color to the social icons when hovered upon

### ISSUE THREAD

**Issue by mukul314** [Resourcio-Community/Resourcio_Community-Website#178]
## Description

**Is your feature request related to a problem? Please describe.**
Currently when we hover over the social icons in the footer they change their size, we can also a nice color to them which is according to their official brand color.

**Describe the solution you'd like**
adding suitable colors while hovering

**Additional Notes** (optional)
I'd like to work on it under GSSOC'23 if you approve @Abhirup-02 .

**Comment by zeitgeistxx** [comment]
Somebody is already working on that
