### ISSUE TITLE
[BUG] Unnecessary messages in console

### ISSUE THREAD

**Issue by AmanSingh6574** [Resourcio-Community/Resourcio_Community-Website#179]
## Description

**Describe the bug:**
Due an error the message is coming in console infinite times

## Screenshots

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/113782984/075797c0-6baf-4484-aeb1-704deef27bc1).

**Additional context:**
pls assign me this issue under GSSOC23 @Abhirup-02

**Comment by zeitgeistxx** [comment]
It's not a bug within the code, it's happening due to 'number-generator' package

**Comment by AmanSingh6574** [comment]
it can be resolved using a meta tag

**Comment by zeitgeistxx** [comment]
Fix it  then.

**Comment by zeitgeistxx** [comment]
It wasn't there before. Is it because of Policy change? @AmanSingh6574

**Comment by AmanSingh6574** [comment]
Might be possible
