### ISSUE TITLE
Updation on the navbar-[GSSOC'23]

### ISSUE THREAD

**Issue by bishakhne0gi** [Resourcio-Community/Resourcio_Community-Website#18]
1. Make the navbar static, or else the user has to go to the header to navigate.
2. Moving the routes to center and keeping the login as it is.
3. The logo is misfitted in the navbar.

**Comment by SINJINI-G** [comment]
I want to work on this issue.. can you please assign this to me for gssoc 2023? @Abhirup-02

**Comment by bishakhne0gi** [comment]
@SINJINI-G , i am not the admin, @Abhirup-02 is the admin of this repo.

**Comment by adityavpawar** [comment]
I want to work on this issue. because my skill set is related to this stack.

**Comment by vaidehidangi23** [comment]
@Abhirup-02 I can resolve this issue, please assign it to me.

**Comment by zeitgeistxx** [comment]
@bishakhne0gi do one more thing, remove HOME from navbar and make the logo clickable for going to home route.

**Comment by bishakhne0gi** [comment]
@Abhirup-02 check, I
 have made a pr with all the updations.
