### ISSUE TITLE
[FEATURE REQUEST]  Designing a custom 404 page 

### ISSUE THREAD

**Issue by mukul314** [Resourcio-Community/Resourcio_Community-Website#182]
## Description

**Is your feature request related to a problem? Please describe.**
I'd like to create a 404 page for the website, so that the user is redirected to that page if he enters an invalid path

**Describe the solution you'd like**
The theme of the page will conform to the website's theme.

**Additional Notes** (optional)
@Abhirup-02 , if you think that this issue is useful, please assign it to me.

**Comment by zeitgeistxx** [comment]
Already have that
