### ISSUE TITLE
[BUG] Content not in center

### ISSUE THREAD

**Issue by DivyanshiNarang** [Resourcio-Community/Resourcio_Community-Website#183]
## Description
Content is not in the center due to which some of the words are not visible properly.

## Screenshots

<img width="580" alt="Screenshot 2023-06-06 175257" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/74779601/ec75074b-48dc-4080-8bd4-dcf87e1d757c">

<img width="587" alt="Screenshot 2023-06-06 175128" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/74779601/a4375203-de87-468f-946c-742b59a0a729">

## Additional Information

**Device:**
- OS:  Windows
- Browser: Chrome

*Please assign this issue to me under GSSoC'23*
@Abhirup-02

**Comment by zeitgeistxx** [comment]
Fix this then @DivyanshiNarang

**Comment by swayamshreenanda20** [comment]
Hi, I would like to work on the project. Please assign it to me.

**Comment by DivyanshiNarang** [comment]
@swayamshreenanda20, I am currently working on this issue.

**Comment by Snigdha2712** [comment]
please assign this issue to me under gssoc23 @Abhirup-02

**Comment by Pragati-3003** [comment]
@Abhirup-02 ,I would like to work on this issue , please assign me.

**Comment by zeitgeistxx** [comment]
> @Abhirup-02 ,I would like to work on this issue , please assign me.

You can work on this. But I haven't seen this issue happen.
