### ISSUE TITLE
[FEATURE REQUEST] Scroll back to top button

### ISSUE THREAD

**Issue by DivyanshiNarang** [Resourcio-Community/Resourcio_Community-Website#184]
## Description

Addition of Scroll back to top button on Resources page.

**Screenshots **
<img width="960" alt="Screenshot 2023-06-06 180510" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/74779601/c99529fb-21ea-4952-b7d2-da88ffa1c5e9">

*Please assign this to me under @GSSoC'23*
@Abhirup-02

**Comment by zeitgeistxx** [comment]
Somebody is already working on that
