### ISSUE TITLE
Making a new scroll-bar [GSSOC'23]

### ISSUE THREAD

**Issue by bishakhne0gi** [Resourcio-Community/Resourcio_Community-Website#19]
Changing the scrollbar as per the UI to give a smooth effect to it.

**Comment by KAPIL9027** [comment]
Hi @bishakhne0gi, could you please assign this issue to me?

**Comment by bishakhne0gi** [comment]
@Abhirup-02 check once.

**Comment by adityavpawar** [comment]
i can solve this issue can you assign me

**Comment by zeitgeistxx** [comment]
@KAPIL9027 I saw your PR and commented on it, go check it out. As soon as the official tags are released I will assign you to this issue, so look out.

**Comment by KAPIL9027** [comment]
> @KAPIL9027 I saw your PR and commented on it, go check it out. As soon as the official tags are released I will assign you to this issue, so look out.

@Abhirup-02, I have made the new pull request. Please check it out and tell me if you need more changes.

**Comment by zeitgeistxx** [comment]
> > @KAPIL9027 I saw your PR and commented on it, go check it out. As soon as the official tags are released I will assign you to this issue, so look out.
> 
> @Abhirup-02, I have made the new pull request. Please check it out and tell me if you need more changes.

Your PR has been merged.
