### ISSUE TITLE
[BUG] Home Page is not responsive

### ISSUE THREAD

**Issue by crocmons** [Resourcio-Community/Resourcio_Community-Website#197]
Home Page is not responsive also the resources page is not responsive...I would love to solve this issue as a gssoc23 contributor..please assign me this issue so that I can make the website responsive for all devices.
![Screenshot (398)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/106610322/03562463-aa23-4fb2-b559-3754d43f9001)

**Comment by zeitgeistxx** [comment]
It's responsive, you might have zoomed in.
![Screenshot_20230609_012315](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/92736753/98c7dfa1-7d97-49e9-a2d5-413c5dd2dc52)
