### ISSUE TITLE
[STYLE CHANGE] In Contact Us section

### ISSUE THREAD

**Issue by pavitrachavda97** [Resourcio-Community/Resourcio_Community-Website#199]
**Description:**
I want to change styling of contact us section and want it to align center. 

**Reason for Change:**
According to website layout styling of contact us section should be align to center. 

**Current Styling:**
Current styling is left align.

**Proposed Styling:**
I want to see center align.

**Additional Information (optional):**
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/91004608/144643e3-7d48-4d56-83b9-b17706e3e2c8)
I want selected part to be show in center of page.

**Priority Level (optional):**
- [ ] Low
- [x] Medium
- [ ] High

**Comment by zeitgeistxx** [comment]
Somebody is working on footer.
