### ISSUE TITLE
Imrove the contact us part of the home page GSSOC'23

### ISSUE THREAD

**Issue by karthiknadar1204** [Resourcio-Community/Resourcio_Community-Website#20]

**Comment by karthiknadar1204** [comment]
i would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
Make the cards more prominent by storing the individual member data in a card and adding adequte spacing between the cards

**Comment by adityavpawar** [comment]
I can solve this issue. can you assign me this issue

**Comment by khushi767** [comment]
i can work on this issue .can you please assign me for gssoc'23 .

**Comment by zeitgeistxx** [comment]
The idea was to make the contact cards like Google developer student club. So according to that the cards are perfect.
