### ISSUE TITLE
Inline Form Validation

### ISSUE THREAD

**Issue by AlfiyaSiddique** [Resourcio-Community/Resourcio_Community-Website#200]
## Issue
Currently in the signup and login forms the validation message appears after the user hits the signup or login button. I want to make these validation messages appear as the user fills in the forms.  If the constraints are not met the message stays and the user will not be able to submit the form but as soon as the valid input is given the message disappears and the forms can be submitted. This kind of real-time validation will provide a better user experience.

## Screenshot
<img width="302" alt="desktop" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/86224794/9c978365-5d71-4b1f-b7cf-c1fbfe1c6cfb">

## Solution: 
Will implement it using react states

## Request
If you find this functionality worth implementing please assign me this issue under Gssoc'23 label

**Comment by zeitgeistxx** [comment]
No need for that.
