### ISSUE TITLE
[feat]: add skeleton screen animation to resources page

### ISSUE THREAD

**Issue by harmeetsingh11** [Resourcio-Community/Resourcio_Community-Website#201]
## Description
When resources page is loaded, it does not have any loading animation, it looks basic. We need to improve.

### Describe the solution you'd like

Using `react-Ioading-skeleton` library, I will add a skeleton screen animation to resources page it will be more engaging for users. When the page is loaded, it will show skeleton screen animation for 2-3 seconds, then after 2-3 seconds all the resources card will be displayed.

### Screenshots or Mockups
![Capture](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/130365071/2d4ddf00-42d1-444b-ad89-1165e325f8e8)

### Record
- [x] I agree to follow project's contributing guidelines.
- [x] I am a GSSoC'23 Contributor.
- [x] I want to work on this issue.

Please assign me this issue under GSSoC'23.
Thanks

**Comment by zeitgeistxx** [comment]
Lazy loading is already there for the components and also for the images there, so there's no meaning to add skeleton screen.
