### ISSUE TITLE
[FEATURE REQUEST] :Add Like button

### ISSUE THREAD

**Issue by suzy-g38** [Resourcio-Community/Resourcio_Community-Website#202]
## Description

Add a like button or upvote button feature.

**Describe the solution you'd like**

As there is already a backend server in this project we can connect the like feature with the backend.

I would like to work on it under gssoc'23

**Comment by zeitgeistxx** [comment]
What thing will you like?

**Comment by suzy-g38** [comment]
> What thing will you like?

Resources, ofc, this will help everyone evaluate which resources collection is best and eventually in future can show your best collections.

**Comment by zeitgeistxx** [comment]
Resources are not coming from backend....if you want to like, go to GitHub and star the repo
