### ISSUE TITLE
[FEATURE REQUEST] : Add save button to the resources

### ISSUE THREAD

**Issue by suzy-g38** [Resourcio-Community/Resourcio_Community-Website#203]
## Description

**Is your feature request related to a problem? Please describe.**

Add a save button so the user can save the items from the resources.

**Describe the solution you'd like**

As there is already a dedicated server, we can use the server to store the data for a particular user in the backend.

**Describe alternatives you've considered**

We can also use localstorage e for this.

**Additional Notes** (optional)

I would like to wor on it under gssoc'12

**Comment by zeitgeistxx** [comment]
Resources are redirected to GitHub. You can download them there.
