### ISSUE TITLE
[FEATURE REQUEST]  Want to add more thing in navbar

### ISSUE THREAD

**Issue by rani620** [Resourcio-Community/Resourcio_Community-Website#205]
## Description

**Is your feature request related to a problem? Please describe.**
Navbar looks very dull and it is not properly organized . 

**Describe the solution you'd like**
Wanted to add more feature on navbar want to make  it attractive . will give an sort over view and different link of all the navigation page of the website .

## Additional Information

**Screenshots or Mockups** (optional)
![Screenshot (552)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/96174308/2931ddcc-4a42-4fe0-aa9d-4565e27d5ead)

**Priority** (optional)
high

**Comment by zeitgeistxx** [comment]
Not required.
