### ISSUE TITLE
[FEATURE REQUEST]  Want to change contact us section  adding some animation and hover effect

### ISSUE THREAD

**Issue by rani620** [Resourcio-Community/Resourcio_Community-Website#206]
## Description

**Describe the solution you'd like**
Want to add  some animation and style of contact us section . Will add some card design in it . some attractive background

## Additional Information

**Screenshots or Mockups** (optional)
![Screenshot (551)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/96174308/9f47a8d6-d5fe-4782-a983-1f762b4247d6)

**Priority** (optional)
high

**Comment by zeitgeistxx** [comment]
Not required.
