### ISSUE TITLE
[BUG] : validation of sign up page.

### ISSUE THREAD

**Issue by lakshmiprasannakusumanchi** [Resourcio-Community/Resourcio_Community-Website#207]
## Description

**Describe the bug:**
 username,name input accepting even if it is also a digits eg:"1234", And there is no confirm password.

**Expected behavior:**
In the sign up page, the username,name should allow only alphabets and should contain the input of confirm password.

**Actual behavior:**
but it actually accepting username,name with any format.

## Reproduction Steps

**Steps to reproduce the behavior:**
1. Go to 'home page'
2. Click on 'sign in'
3. Click on 'sign up'

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

**Comment by zeitgeistxx** [comment]
No need for confirm password. you can unhide password and check it.

**Comment by zeitgeistxx** [comment]
username may contain numbers. 

But yeah Name should only contain alphabets.

**Comment by lakshmiprasannakusumanchi** [comment]
@Abhirup-02 then I can modify the validation for name-input plz assign this to me under gssoc'23

**Comment by zeitgeistxx** [comment]
@lakshmiprasannakusumanchi  do it.

**Comment by agarwalhimanshugaya** [comment]
i want to add name input validation and also add password confirmation

**Comment by NamandeepNegi** [comment]
hello @Abhirup-02  assign this issue to me, i will add validations using regex or with a third party library Formik with React
