### ISSUE TITLE
Enhance smooth hover effect in category section

### ISSUE THREAD

**Issue by DeveloperAshish8** [Resourcio-Community/Resourcio_Community-Website#208]
## Description

The current hover effect includes a box shadow only where looks minimal.

**Describe the solution you'd like**
I want to add a smooth transition effect along with the box shadow to make it looks attractive. 

## Issue SS
![Screenshot (73)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/90233808/346bbe7c-704e-4f75-ab39-2185e0264445)

**Comment by DeveloperAshish8** [comment]
Hey @Soumyajit2825 , Please assign me this issue under GSSoC

**Comment by zeitgeistxx** [comment]
No need for that.....they are not interactive, giving animations to them might mean wrong.
