### ISSUE TITLE
No back Button to go back to Home From Resources page

### ISSUE THREAD

**Issue by Mudassirkhan2** [Resourcio-Community/Resourcio_Community-Website#21]
No back Button to go back to Home Page from Resources in both mobile and desktop Image Attached  
![Screenshot 2023-05-20 094746](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/106579572/85332f98-bafb-4ad3-865d-c6919d256cdf)
 i Want to work on this issue under GSS0c2023.

FeedBack :  resources  page looks weird when compared to Home Page. It looks like we are transformer to another planet😜.

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23

**Comment by zeitgeistxx** [comment]
Already assigned to another contributor.
