### ISSUE TITLE
[FEATURE REQUEST]: Add Social Icons with Link Instead of Using View Profile Button

### ISSUE THREAD

**Issue by NarendraKoya999** [Resourcio-Community/Resourcio_Community-Website#210]
## Description

**Is your feature request related to a problem? Please describe.**
- **Add Social Icons with Link Instead of Using View Profile.**
- **Also, Include Multiple Social  Icons with Source Links like `LinkedIn, GitHub, Mail` for Better Advanced Communication.**
- **It elevates Better Enhancement.**

**Describe the solution you'd like**
- **Add Multiple Social Icons above Mentioned Instead of Using View Profile Button.**

**Describe alternatives you've considered**

## Additional Information

**Context**
- **Add Multiple Social Icons to Profile Cards are Much Easier to Maintain Better Communication.**

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
<img width="717" alt="resourcio-2" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/84512164/98fa74a4-cc9e-467e-bf75-964bbf5f9937">

**Priority** (optional)
**`Priority Level- Medium`**
**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by zeitgeistxx** [comment]
That won't be needed.
