### ISSUE TITLE
[BUG] Website does not have proper meta tags

### ISSUE THREAD

**Issue by Avinash905** [Resourcio-Community/Resourcio_Community-Website#212]
## Description

**Describe the bug:**
The website does not have meta tags like open graph, twitter, etc. This means that the website is less likely visible in search results, and users are less likely to click on the website's links.

**Expected behavior:**
The website should contain important meta tags. This will help the website rank higher in search results and attract more visitors.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by zeitgeistxx** [comment]
We will look after the SEO, don't worry
