### ISSUE TITLE
Adding dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [Resourcio-Community/Resourcio_Community-Website#213]
*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@Abhirup-02 please assign me this issue under gssoc'23.

**Comment by zeitgeistxx** [comment]
There are some major version changes in some of the dependencies, which doesn't support the previous version functions......so we have to go through the whole project to change them.

So right now I am thinking to not add the bot. Thanks
