### ISSUE TITLE
[FEATURE REQUEST] Adding Contributor List in the Readme

### ISSUE THREAD

**Issue by abhi03ruchi** [Resourcio-Community/Resourcio_Community-Website#218]
## Description

**Is your feature request related to a problem? Please describe.**
I would like to add a contributor List in the Readme section. A  Contributors List promotes a positive and inclusive environment, fostering further participation and enhancing the project's success.

## Additional Information

**Context**
Sample:
<img width="784" alt="Screenshot 2023-06-17 at 1 06 34 AM" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/105661636/3d675e36-758f-467a-97a8-ab238370d15f">

**Priority** (optional)
Medium

**Additional Notes** (optional)
Plz assign this task to me under gssoc'23.

**Comment by zeitgeistxx** [comment]
Not needed
