### ISSUE TITLE
[STYLE CHANGE] Adding Flip cards in the Categories section . 

### ISSUE THREAD

**Issue by abhi03ruchi** [Resourcio-Community/Resourcio_Community-Website#219]
**Description:**
Enhance the Categories section by Adding Flip cards in it.

**Reason for Change:**
This kind of animated **_on-hover flip cards effect_** would improve user experience and engagement.

**Current Styling:**

<img width="1269" alt="Screenshot 2023-06-17 at 1 14 06 AM" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/105661636/5dd034fd-d0b4-4343-8463-e433ad4700fa">

**Proposed Styling:**
https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/105661636/28efcf63-6ba5-4fdf-8eb8-d3a7368a35f4 

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

Plz assign this issue to me under gssoc'23.

**Comment by zeitgeistxx** [comment]
Have you made any progress @abhi03ruchi

**Comment by abhi03ruchi** [comment]
yes , I will submit the work by 25th for sure.

**Comment by zeitgeistxx** [comment]
@abhi03ruchi  keep the image and heading in front and description on the back side.

**Comment by abhi03ruchi** [comment]
I have created a pr, plz review and merge it.

**Comment by zeitgeistxx** [comment]
@abhi03ruchi cards are stacking on top of each other in smaller view. fix that please
![Screenshot 2023-06-27 024014](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/92736753/8897a9fc-380e-4f9d-9959-171ef411e60c)
