### ISSUE TITLE
Adding forget password and OAuth with google

### ISSUE THREAD

**Issue by Aleesha2002** [Resourcio-Community/Resourcio_Community-Website#222]
**## Description:**
Enhance the signup and login procedure by adding login and signup with google. 
And also adding the forget password functionality.

## Additional Information

**Context:**
By adding these functionalities we can provide a great user experience.

**Current sign up:** 
![Screenshot from 2023-06-17 18-09-46](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/107275325/2bdd5340-edd0-4b58-a01c-b86988511320)
Here at the end we can add these functionalities.

**Current login:**
![Screenshot from 2023-06-17 18-12-03](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/107275325/d628647e-eed2-4d9a-bca9-0388ffd6e93f)

**Priority Level (optional):**
 Medium

**Comment by Aleesha2002** [comment]
Please assign this issue to me

**Comment by zeitgeistxx** [comment]
I will take care of that.
