### ISSUE TITLE
[BUG] Add Back TO Home Button on ' 404' Page Not Found .

### ISSUE THREAD

**Issue by abhi03ruchi** [Resourcio-Community/Resourcio_Community-Website#223]
## Description

**Describe the bug:**
The ' 404' Not Found Page, does not have a back-to-home button. This bug may confuse and frustrate the user [what to do now]??
To help the user incase of unknown routes, it is important to add a back-to-homePage button.

## Screenshots
<img width="1045" alt="Screenshot 2023-06-18 at 1 47 48 AM" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/105661636/aa1c89f9-9fc0-4a20-b247-9705cceff79d">

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

**Comment by zeitgeistxx** [comment]
Just hit browser back button. There's no sense in putting back back button in not found page.
