### ISSUE TITLE
[STYLE CHANGE] Toggle visibility eye button picture

### ISSUE THREAD

**Issue by Vanoita** [Resourcio-Community/Resourcio_Community-Website#224]
**Description:**

The icon that controls the visibility of an object, represented by an eye symbol, remains unchanged despite its functionality being intact. Even though the icon successfully performs the action of hiding or showing of password, the image itself does not undergo any noticeable alteration or transformation.

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/93696376/a29e7a48-4921-42d3-a7c5-f23a54e377b1)
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/93696376/59e83b33-5c96-4fdd-a109-72416c609329)

**Reason for Change:**

Better and intuitive user experience

**Current Styling:**

Currently, the eye icon remains the same for both hide and show passwords.

**Proposed Styling:**

password masked == open eye icon
password shown == closed eye icon 

**Priority Level (optional):**

- [x] Low
- [ ] Medium
- [ ] High

**Comment by zeitgeistxx** [comment]
@Vanoita that's nice....
Work on it

**Comment by zeitgeistxx** [comment]
As we are using fontawesome icons there, keep the same type of icon there for eye-closed.
