### ISSUE TITLE
Resource card ui improvement

### ISSUE THREAD

**Issue by SubhamB2003** [Resourcio-Community/Resourcio_Community-Website#228]
**Description:**
Hey, I want to improve the resource section card ui.

Previous
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/94003231/ad28f58c-6963-4320-bd11-6899aa1f7d71)

Now
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/94003231/511cf641-4b95-4dd9-9177-f4dfeb493d3f)

If you think it is ok then can please assign it to me under GSSOC'23?

[Provide a clear and concise description of the style change you are requesting.]

**Reason for Change:**

[Explain the reasons behind the requested style change, such as usability, branding, or user experience.]

**Current Styling:**

[Describe the current styling that needs to be changed.]

**Proposed Styling:**

[Describe the desired styling or changes you would like to see.]

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by zeitgeistxx** [comment]
To be honest the present card looks better.
