### ISSUE TITLE
[FEATURE REQUEST]  Add Captcha it the sign up page

### ISSUE THREAD

**Issue by Manice18** [Resourcio-Community/Resourcio_Community-Website#229]
## Description

**Is your feature request related to a problem? Please describe.**
Captcha must be present in the website to check whether the user creating an account is a human and not a bot.

**Describe the solution you'd like**
I would like to add captcha verification below the password section, above the sign up button

**Describe alternatives you've considered**
none

## Additional Information

**Priority** (optional)
High

**Comment by zeitgeistxx** [comment]
That will be too hectic.
