### ISSUE TITLE
need a button sign in page to home page

### ISSUE THREAD

**Issue by mandliyarajendra11** [Resourcio-Community/Resourcio_Community-Website#23]
when we click on sign in page there is no option to go back to home page 

i can work on this issue can you assign me this issue under gssoc 23

![Screenshot (95)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/119125519/4f9197c7-8eeb-49b9-be9d-d9f6b4b75c9b)

**Comment by adityavpawar** [comment]
i can solve this issue can you assign me this issue

**Comment by zeitgeistxx** [comment]
@mandliyarajendra11 are you working on this issue?

**Comment by mandliyarajendra11** [comment]
@Abhirup-02  yes sir even fixed
