### ISSUE TITLE
[BUG] Sign In form not validate E-mail field

### ISSUE THREAD

**Issue by Geeta259** [Resourcio-Community/Resourcio_Community-Website#230]
## Description

Sign in form not validate E-mail field !
![Screenshot (392)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/75520947/c6f9258a-c711-49fd-bdab-db6cec1b7b5c)

@Abhirup-02 I would like to contribute on this project under GSSOC'23 by add a proper validation in both field
Empty validation add & E-mail correct format validation add
Show error message below the fields with highlighted that field with red border outside the field.

**Comment by zeitgeistxx** [comment]
There's no meaning in adding validation in sign-in..............only sign-up validation seems perfect.
