### ISSUE TITLE
[STYLE CHANGE] Upgrade Error Notifications to React Toastify Notifications. {GSSoC'23}

### ISSUE THREAD

**Issue by GVishnudhasan** [Resourcio-Community/Resourcio_Community-Website#232]
**Description:**

Change the user not found error event notification from a simple notification to a React Toastify notification to enhance the visual appearance.

**Reason for Change:**

Description:

Change the user not found error event notification from a simple notification to a React Toastify notification to enhance the visual appearance.

Reason for Change:

The current simple notification style lacks visual appeal and may not effectively capture the user's attention. By using React Toastify notifications, we can improve the overall user experience and provide a more visually appealing way to communicate error events.

**Current Styling:**

Currently, when a user is not found, or any error events a simple notification appears there itself. The notification is plain and lacks any specific styling or animation effects.

**Proposed Styling:**

The proposed styling involves using React Toastify notifications for the user not found error event. React Toastify provides customizable, animated notifications that can be styled to match the application's design and branding. The notification should have a distinct appearance to differentiate it from other notifications.

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

**Possible Implementation Approach:**

1. Install the React Toastify package using a package manager like npm or yarn.
2. Create a new component or modify the existing notification component to use the React Toastify API.
3. Customize the notification appearance and animation according to the application's design.
4. Update the error handling logic to trigger the React Toastify notification for the user not found error event.
5. Test the implementation thoroughly to ensure proper functionality and visual appeal.

**Additional Information:**

Please assign this issue to me under GSSoC'23 so that I could change the style ASAP.

**Comment by zeitgeistxx** [comment]
We don't need that notification. You can see it everywhere, it will look so common.
