### ISSUE TITLE
[BUG] Navbar Colliding with Team Section while Scrolling. {GSSoC'23}

### ISSUE THREAD

**Issue by GVishnudhasan** [Resourcio-Community/Resourcio_Community-Website#233]
## Description

**Describe the bug:**
The navbar is colliding with the team section in the main page while scrolling.

**Expected behavior:**
The navbar and the team section should not overlap or collide while scrolling. There should be sufficient spacing between them to ensure a smooth and visually pleasing user experience.

**Actual behavior:**
The navbar overlaps with the team section when scrolling, resulting in a visual collision and potentially obstructing the content.

## Reproduction Steps

**Steps to reproduce the behavior:**
1. Go to the main page.
2. Scroll down the page.
3. Observe the navbar and the team section.

**Expected result:**
At each step:

1. The navbar should stay fixed at the top of the page.
2. The team section should smoothly scroll beneath the fixed navbar, without any overlap.3. 

**Actual result:**
At each step, The navbar overlaps with the team section while scrolling, causing a visual collision.

## Screenshots

![Screenshot 1945-03-31 at 5 24 31 PM](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/94748228/733a2cfd-45ce-4d9c-8982-60becf1504c0)

## Additional Information

**Device (please complete the following information):**
- OS: macOS
- Browser: Safari
- Version: Latest

**Additional context:**
Please assign this issue to me under GSSoC'23 so that I could take this and upon this and fix it ASAP.

**Comment by zeitgeistxx** [comment]
@GVishnudhasan that's impossible.....navbar has high z-index. No one faced this issue.
