### ISSUE TITLE
[FEATURE REQUEST] Add a CodeQL Workflow

### ISSUE THREAD

**Issue by abhinav-m22** [Resourcio-Community/Resourcio_Community-Website#235]
## Description

The repository has javascript code but it lacks workflow for code inspection.

The codeql.yml workflow file will be added by me to automate security checks.

CodeQL is a code analysis tool, to find vulnerabilities in programs.
The code will be examined, and the results will be presented as code scanning alerts.
Every push, commit, and pull request that uses GitHub actions will have it enabled.

I want to work on this issue, Please assign it to me under GSSoC'23

**Comment by zeitgeistxx** [comment]
@abhinav-m22 that's a nice point. Do it.
