### ISSUE TITLE
[FEATURE REQUEST] Convert Images to WebP Format for Improved GitHub Project Performance

### ISSUE THREAD

**Issue by Avinash905** [Resourcio-Community/Resourcio_Community-Website#236]
## Description

**Is your feature request related to a problem? Please describe.**
Currently, the images in our GitHub project are stored in the PNG/JPG image format. However, we would like to convert them to the more efficient WebP format. This conversion will help us reduce file sizes while maintaining image quality, leading to improved website performance and faster loading times.

**Describe the solution you'd like**
In order to optimize our project's image assets and enhance user experience, I propose converting all the PNG/JPG images to WebP format.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by zeitgeistxx** [comment]
I am already doing it from my end.
