### ISSUE TITLE
Adding slide transition animation effects in the front page of the website

### ISSUE THREAD

**Issue by Illaf** [Resourcio-Community/Resourcio_Community-Website#237]
**Description:**

[Provide a clear and concise description of the style change you are requesting.]

**Reason for Change:**
The website looks a bit static and less interesting displaying only the information. animations help user visually digest information. Static websites seem less attractive to the user.
[Explain the reasons behind the requested style change, such as usability, branding, or user experience.]

**Current Styling:**
No animation and sliding effects are added to the entire website.
[Describe the current styling that needs to be changed.]

**Proposed Styling:**
In the first page ,I will add left sliding effect to the text and and button with a slight delay and then right sliding effect to the event box with opacity initially zero.
[Describe the desired styling or changes you would like to see.]

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by zeitgeistxx** [comment]
@Illaf  you are up for the issue.
