### ISSUE TITLE
adding read more and read less option in the divs of the resources section.

### ISSUE THREAD

**Issue by Illaf** [Resourcio-Community/Resourcio_Community-Website#239]
## Description

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem or limitation that the requested feature would address.
The divs of the resources section are not of the same length due to different amount of content in them
**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.
Adding a "...Read more"  option in the paragraphs so that all divs become of equal length.
**Describe alternatives you've considered**
I have also considered giving padding to the image in the div
## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).
high
**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by zeitgeistxx** [comment]
Someone already did that.
