### ISSUE TITLE
Adding Hover Effect on Contact Us Cards [GSSOC'23]

### ISSUE THREAD

**Issue by sshiwangi** [Resourcio-Community/Resourcio_Community-Website#24]
I would like to add a hover effect on the cards of the contact us section so that it looks something like this
![Screenshot 2023-05-20 102351](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/77545230/f408f219-d377-4d56-ada4-75a92b05237e)

Please assign me this issue under GSSOC'23

**Comment by zeitgeistxx** [comment]
@sshiwangi hey, are you still willing to work on this issue. Please let me know.

**Comment by sshiwangi** [comment]
> @sshiwangi hey, are you still willing to work on this issue. Please let me know.

I will push it in an hour. Got indulge with some college work.

**Comment by sshiwangi** [comment]
Hey @Abhirup-02 should i change the api url back to what it was as mentioned in .env.example?

**Comment by zeitgeistxx** [comment]
> Hey @Abhirup-02 should i change the api url back to what it was as mentioned in .env.example?

It's not really clear what you are saying. What do you mean back to what it was.

**Comment by sshiwangi** [comment]
> > Hey @Abhirup-02 should i change the api url back to what it was as mentioned in .env.example?
> 
> It's not really clear what you are saying. What do you mean back to what it was.

Oh, nothing I got a little confused. Created a pr please check.
