### ISSUE TITLE
[STYLE CHANGE]

### ISSUE THREAD

**Issue by kritriv** [Resourcio-Community/Resourcio_Community-Website#240]
**Description:**

On the resources Page, Resources cards need to improve 

**Reason for Change:**

As the Current card design is looking too outdated and not well

**Priority Level (optional):**

- [x] High

@bishakhne0gi @Avinash905 @r3yc0n1c @DivyanshiNarang @pranav-iitr 
Please assign this issue to me under GSSOC'23

**Comment by zeitgeistxx** [comment]
No need.
