### ISSUE TITLE
[FEATURE REQUEST] : Add Code Splitting

### ISSUE THREAD

**Issue by Manice18** [Resourcio-Community/Resourcio_Community-Website#243]
## Description

**Is your feature request related to a problem? Please describe.**
When the website is loaded, unnecessary components which are not required at that moment are loaded, thus reducing the optimisation of the website. Here a screenshot:
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/91601706/e6dd6a61-6fd1-452b-8fab-7ad351022527)

**Describe the solution you'd like**
I will like to implement the concept of code splitting with the help of React Lazy, suspense with proper fallback

## Additional Information

**Context**
This will greatly increase the optimisation of the website thus making it faster to load.

**Comment by zeitgeistxx** [comment]
It is already there.
