### ISSUE TITLE
[STYLE CHANGE] Add a Carousel feature to Team section  

### ISSUE THREAD

**Issue by Ilinapradhan** [Resourcio-Community/Resourcio_Community-Website#244]
**Description:**

Instead of staking all the members cards in column we can turn it into a carousel so that we can slide and visit each card , 

**Reason for Change:**

The website will look more dynamic and modern and will will give a better UI /UX 

@Resourcio_Community-website assign it to me

**Comment by zeitgeistxx** [comment]
@Ilinapradhan  keep 3 members in front and rest in the slide.

**Comment by zeitgeistxx** [comment]
@Ilinapradhan  what's your update?

**Comment by Pragati-3003** [comment]
> @Ilinapradhan what's your update?

@Abhirup-02 ,I would like to work on this issue , so , please assign this issue to me .

**Comment by zeitgeistxx** [comment]
@Pragati-3003 yeah, you can work on this issue.
