### ISSUE TITLE
[FEATURE REQUEST] Dockerize the server config

### ISSUE THREAD

**Issue by abhinav-m22** [Resourcio-Community/Resourcio_Community-Website#245]
I want to containerize the application by creating a Dockerfile and a corresponding dockerignore file.

In the repository, the **server** folder can be containerized, so that once the image is spun up, it will keep on running and connected to the frontend.

Dockerizing the application will enable us to package it along with its dependencies into a container, ensuring consistent and reliable deployments across different environments.
By using Docker, we can easily spin up and scale multiple instances of the application, making it more robust and efficient.

This issue aims to implement Dockerization for the application, streamlining our deployment workflow and enhancing its overall performance and portability.

**Comment by zeitgeistxx** [comment]
no need for that now.
