### ISSUE TITLE
need a close button in responsive navbar

### ISSUE THREAD

**Issue by mandliyarajendra11** [Resourcio-Community/Resourcio_Community-Website#25]
When we click on the menu button, the menu opens, and there is also a close button available there.

![Screenshot (96)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/119125519/aa6de6c3-d846-4347-b872-d71ba7dc9bd3)

**Comment by adityavpawar** [comment]
i have already worked on this can you please assign me this issue

**Comment by DhruvitPatel007** [comment]
I'm a gssoc'23 contributor.I would like to contribute to this issue under gssoc.
