### ISSUE TITLE
CHANGE IN FOOTER DESIGN

### ISSUE THREAD

**Issue by zeitgeistxx** [Resourcio-Community/Resourcio_Community-Website#253]
**Proposed Styling:**

- Current height of the footer is too long, make it half of the current length. 
- Reduce the font-size of footer accordingly.
- Follow the styling as shown in the screenshot below.
- Make it responsive for every screen size.

**Screenshot**

![Screenshot 2023-06-24 194359](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/92736753/576fa0cd-e52a-4dc1-b848-6afe57e6e90e)

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

**Issue will be assigned as first come first serve basis.**

**Comment by Riyazul555** [comment]
Hey @Abhirup-02  I wanted to work on this issue .....please assign me this

**Comment by Riyazul555** [comment]
Hey @Abhirup-02 do you want to shift the social icons on the right as suggested in the screen shot ?

**Comment by zeitgeistxx** [comment]
Yes

**Comment by Riyazul555** [comment]
@Abhirup-02 please check pR #265 for the changes

**Comment by sanaya56** [comment]
Hey @Abhirup-02 please assign this task to me

**Comment by zeitgeistxx** [comment]
no @Riyazul555  is still working on it i guess.

**Comment by Riyazul555** [comment]
Yep @Abhirup-02 but little busy with my exams 😅

**Comment by zeitgeistxx** [comment]
Ok no problem

**Comment by Pragati-3003** [comment]
> Ok no problem

@Abhirup-02 , I would like to work on this issue , please assign this to me  if this issue is open.

**Comment by zeitgeistxx** [comment]
@Pragati-3003 yeah go on.
