### ISSUE TITLE
[STYLE CHANGE] improving UI pages -[home]

### ISSUE THREAD

**Issue by Piyusharora2003** [Resourcio-Community/Resourcio_Community-Website#255]
1.  I think its better we provide a poster of gssoc here and over which we provide the content

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/74443858/4036ddf5-9e6a-45f9-b18d-b7efb5fa7b87)

2. Adding Links to the Categories boxes

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/74443858/4f49a5fb-14a9-417b-ad8f-7cd2e54f9cb9)

3. Navbar hover effect dissimalrity issues 

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/74443858/8736e765-7cd3-45f5-b67a-6dc7df2ff97f)
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/74443858/8eb313e7-563f-4eb6-8c5d-28250883851f)

Assign me this issue

**Comment by zeitgeistxx** [comment]
No need.
