### ISSUE TITLE
ADD DARK MODE TO WHOLE WEBSITE

### ISSUE THREAD

**Issue by zeitgeistxx** [Resourcio-Community/Resourcio_Community-Website#256]
- Make use of ContextAPI to have the theme available to every component
-  Store the theme in localStorage and get it at time of mounting the app.
- Place the button in a relevant position
- Make theme change button as shown below (You can tweak a little bit design as your preference)

https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/92736753/4ec542ed-c13c-4b05-8f43-820bf974e13c

**Comment by Devil1205** [comment]
I would like to work on this feature, please assign.

**Comment by mandliyarajendra11** [comment]
please assign me this issue @Abhirup-02

**Comment by zeitgeistxx** [comment]
@Devil1205 go for it

**Comment by zeitgeistxx** [comment]
So I have already created ThemeContext, do check it out and use it properly.

**Comment by zeitgeistxx** [comment]
@Devil1205  I have already created the Theme change button in the component. Do use it.

**Comment by Devil1205** [comment]
> @Devil1205 I have already created the Theme change button in the component. Do use it.

Alright, will use it.
