### ISSUE TITLE
ADD FAQ SECTION

### ISSUE THREAD

**Issue by zeitgeistxx** [Resourcio-Community/Resourcio_Community-Website#257]
- Make a FAQ section
- Make a separate component for FAQ and  add it after Team component.
- We are already using Material UI, so use Accordion from Material UI to show the questions and answers.
- Use controlled accordion along with customization of your choice
- The FAQ doc is here [FAQ.docx](https://github.com/Resourcio-Community/Resourcio_Community-Website/files/11857801/FAQ.docx)

For info about Accordion visit https://mui.com/material-ui/react-accordion/

**Comment by Kalyan-velu** [comment]
@Abhirup-02 I want to work on this

**Comment by zeitgeistxx** [comment]
hey @Kalyan-velu you are up for the issue.

**Comment by Kalyan-velu** [comment]
Thanks @Abhirup-02
