### ISSUE TITLE
[FEATURE REQUEST] Adding Navbar, footer on resources page along with the pagination/search bar.

### ISSUE THREAD

**Issue by Akanksha-202** [Resourcio-Community/Resourcio_Community-Website#259]
## Description

The resources page doesn't merge with the whole website, Including the navbar and footer will make it whole! Adding pagination is recommende as in future, the resources might increase and keeping all the stuff on a page will not look that great.

**Describe the solution you'd like**
Importing the navbar and footer of the main page to the resources section too, and adding pagination to set only 6 cards on a page, will let users explore the website more, and keeping only certain cards on a page will let them concentrate more as well.

**Describe alternatives you've considered**
 Instead of pagination, can attach a search bar instead as well.

## Additional Information

**Context**
It will enhance the user experience.

Please assign this issue to me under GSSoC'23 label :)

**Comment by zeitgeistxx** [comment]
We will release new design for that and then create an issue.
