### ISSUE TITLE
Update on Category Section 

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [Resourcio-Community/Resourcio_Community-Website#27]
I want to update on resource section especially the card section. I want to contribute under GSSoC '23 as a contributor. 

![Resource section GSSoC '23](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/94108574/0dc4b3e3-fb04-4410-82b4-e859efa46785)

Allow me to bring some change here .

**Comment by zeitgeistxx** [comment]
This issue is already fixed
