### ISSUE TITLE
[FEATURE REQUEST] : Added dark theme.

### ISSUE THREAD

**Issue by BhartiNagpure** [Resourcio-Community/Resourcio_Community-Website#274]
## Added toggle button for Dark and Light Theme

**Is your feature request related to a problem? Please describe.**
We know that nowadays all website are created in two theme dark and light and this website is only for light theme.

**Describe the solution you'd like**
 I would tike to add toggle button for dark theme and light theme.

**Describe alternatives you've considered**
It gives nice look to website and user can also see this website in two theme.

## Additional Information

**Context**

**Potential Implementation** (optional)

**Screenshots or Mockups** (optional)

**Priority** (optional)
High

**Additional Notes** (optional)

**Comment by zeitgeistxx** [comment]
Someone is already assigned for this.
