### ISSUE TITLE
Add validation to email and password in sign in page

### ISSUE THREAD

**Issue by Avinash905** [Resourcio-Community/Resourcio_Community-Website#28]
There is no validation to the email and password in sign in page.
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Avinash905** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by zeitgeistxx** [comment]
I don't think validation is necessary for sign in page, it is only relevant for sign up page i think.
