### ISSUE TITLE
NAVBAR REDESIGN

### ISSUE THREAD

**Issue by zeitgeistxx** [Resourcio-Community/Resourcio_Community-Website#288]
- Do not change any theme of the navbar.
- Follow the given screenshots to implement the design.
- Make the new design responsive for all screens.
- Add Blog, FAQ, Achievements in the dropdown menu.
- Leave the space for Theme change button.

![WhatsApp Image 2023-07-01 at 15 58 53](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/92736753/e388cc8c-25e3-4b6a-92d3-1b3cc95d569e)

![WhatsApp Image 2023-07-01 at 16 02 26](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/92736753/9c273850-8c67-4220-ada4-4c96f395b232)

- [ ] Low
- [ ] Medium
- [x] High

**Comment by harmeetsingh11** [comment]
@Abhirup-02 Can I work on this issue? I'll try to resolve the issue. Please assign me under GSSoC'23.

**Comment by zeitgeistxx** [comment]
ok then @harmeetsingh11, resolve this issue.

**Comment by abhinav2712** [comment]
is @harmeetsingh11 still working  on this?

**Comment by harmeetsingh11** [comment]
Yes @abhinav2712
