### ISSUE TITLE
REDESIGN OF RESOURCES PAGE

### ISSUE THREAD

**Issue by zeitgeistxx** [Resourcio-Community/Resourcio_Community-Website#289]
- Follow the given design below.
- Responsiveness is needed.

![resource page](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/92736753/ab916481-fa87-4183-afc2-0f741fa6ad7d)

**Comment by Devil1205** [comment]
I would like to design this page. Please kindly assign.

**Comment by zeitgeistxx** [comment]
yeah @Devil1205, have at it.
