### ISSUE TITLE
Add validation to email and password in sign up page

### ISSUE THREAD

**Issue by Avinash905** [Resourcio-Community/Resourcio_Community-Website#29]
There is no validation to the email and password in sign up page.
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Uj293** [comment]
add validation and also a pop up message to your sign up page that shows signup successfully 
please assign this to me i can easily solve it using simple javascript

**Comment by zeitgeistxx** [comment]
@Avinash905  i will let you know once we get the proper official  tags, as of now we are not gonna use temporary tags

**Comment by Avinash905** [comment]
> @Avinash905 i will let you know once we get the proper official tags, as of now we are not gonna use temporary tags

Ok sure
