### ISSUE TITLE
[STYLE CHANGE] Add hover effect on social icons

### ISSUE THREAD

**Issue by sumitkr2000** [Resourcio-Community/Resourcio_Community-Website#293]
**Description:**

Hey, I want to add a hover effect on social icons. When the user hovers over the social icons the color changes to its respective official color. Please assign me this issue. Thank you!

**Reason for Change:**

Better UI

**Current Styling:**

No hover effect

**Proposed Styling:**

Color changes to the respective color of the social media.

**Screenshots or Design Mockups (optional):**

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/100675296/00d11178-515c-406e-ab20-435c0a17a76e)

On hover:-

![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/100675296/478f9446-e8b2-404d-9be8-f752db80f444)

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [x] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by zeitgeistxx** [comment]
hey @sumitkr2000 go for it.
