### ISSUE TITLE
 Add Newsletter Subscription Feature Linked to Hashnode Newsletter

### ISSUE THREAD

**Issue by Nishitbaria** [Resourcio-Community/Resourcio_Community-Website#297]
## Description

Currently, our website lacks a newsletter subscription feature that allows visitors to subscribe and receive updates from our Hashnode newsletter. This feature is crucial for expanding our reach and engaging with our audience effectively. This issue aims to address this functionality gap by integrating a newsletter subscription form on our website that will seamlessly connect with our Hashnode newsletter.

**Expected Behavior:**
1. Visitors should be able to enter their email addresses in a newsletter form on our website.
2. Upon submitting their email addresses, visitors should receive a confirmation email from Hashnode, prompting them to confirm their subscription.
3. After confirming their subscription, visitors should start receiving our Hashnode newsletter emails regularly.

**Describe the solution you'd like**
To implement this feature, we need to follow these steps:
1. Design and implement a newsletter subscription form on our website, where visitors can enter their email addresses.
2. Integrate the form with Hashnode's newsletter subscription API to forward the submitted email addresses.
3. Configure the Hashnode newsletter settings to send a confirmation email to new subscribers, containing a confirmation link.
4. Ensure that the confirmation link validates the subscription and adds the subscriber to our Hashnode newsletter recipient list.
5. Confirm that the subscription is successful by testing the process with a test email address and verifying that the confirmation email is received and processed correctly.

**Describe alternatives you've considered**

## Additional Information

The integration with Hashnode is essential because it provides a reliable and efficient platform for managing and sending newsletters. By automating the process, we can focus on creating valuable content and delivering it to our subscribers without any manual intervention.

**Context**
it would be great to incorporate some form of email address validation on the subscription form to minimize the chance of incorrect or spam addresses being submitted. This will help maintain a high-quality subscriber list.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
This issue should be assigned a medium priority level as it directly affects our communication and engagement with our audience.
**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by Nishitbaria** [comment]
@Abhirup-02 ,please assign me this issue,i will create pull request asap

**Comment by zeitgeistxx** [comment]
We will have our own Hashnode API integration, after that we will think about newsletter subscription

**Comment by zeitgeistxx** [comment]
If you are willing to build Hashnode API integration with Apache client let me know.

I will create an issue then

**Comment by Nishitbaria** [comment]
I can integrate without api and hashnode api doesn't  provide newsletter,but i can provide it if you assign me this issue,i just need your hashnode public .dev url

**Comment by zeitgeistxx** [comment]
I am not talking about newsletter.

I am talking about blog integration using Hashnode api
