### ISSUE TITLE
Add Footer Section GSSOC'23

### ISSUE THREAD

**Issue by tanya2203** [Resourcio-Community/Resourcio_Community-Website#31]
I want to add a footer section containing additional information, links, and contact details  to provide users with supplementary information and navigation options.

Within the footer, you may find various components, one of which is the "Contact Me" section. This section typically includes contact information such as an email address, phone number, or a contact form through which users can reach out to the website/app owner or administrator. 
Please assign me this issue for GSSOC'23.

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by adityavpawar** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by Sathvik902** [comment]
@r3yc0n1c @ronitblenz I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by zeitgeistxx** [comment]
Not required.
