### ISSUE TITLE
Create a sticky Navbar --(GSSoC'23)

### ISSUE THREAD

**Issue by Geeta259** [Resourcio-Community/Resourcio_Community-Website#32]
Navbar position not fixed while navigate up and down .Want to resolve this issue.

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by adityavpawar** [comment]
i can solve this issue can you please assign me this

**Comment by Sathvik902** [comment]
@r3yc0n1c @ronitblenz , I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by Avinash905** [comment]
I would like to work on this issue under GSSOC'23

**Comment by zeitgeistxx** [comment]
already assigned to another contributor.
