### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Debaditya-Som** [Resourcio-Community/Resourcio_Community-Website#336]
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/121785700/e4fb77aa-b815-4fb8-8a98-ff59219400d6)

The updated Resourcio Community logo is not visible and is showing error while loading

**Comment by zeitgeistxx** [comment]
@Debaditya-Som it's working perfectly, check your internet connection and reload.
