### ISSUE TITLE
Creation of 'Continue with Google' button

### ISSUE THREAD

**Issue by SuperGrut** [Resourcio-Community/Resourcio_Community-Website#34]
A user would much rather prefer to sign in with Google because it is fast and simple unlike registering manually by typing in the Full Name, email address, password, and confirm password and verifying email.

So, we can create a button that `Continue with Google`.
![continuewithgoogle](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/72060440/f65de929-064c-4676-96be-40cb1cd7938a)

### PS: I would like to implement the button. So maintainer could you please assign the issue to me.

**Comment by zeitgeistxx** [comment]
Don't want google sign in now.
