### ISSUE TITLE
Update Twitter Logo in the footer section to 'X'

### ISSUE THREAD

**Issue by Debaditya-Som** [Resourcio-Community/Resourcio_Community-Website#343]
**Description**

The current logo of the Twitter icon on the website needs to be updated to the new 'X' logo. This change will ensure that the website remains up-to-date with the latest branding of Twitter. The new 'X' logo reflects the current design and branding guidelines of Twitter.

**Proposed Solution:**

Replace the current Twitter logo with the official 'X' logo of Twitter.
Update the website's CSS or image asset to reflect the new logo.

**Additional Information:**

Twitter's official branding guidelines can be found [here](https://brand.twitter.com/en.html).
The 'X' logo image file can be obtained from the official Twitter branding resources.

**Attachments:**
![twitter-x-logo-0339F999CF-seeklogo com](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/121785700/98596fdd-dfb9-4ff5-bd37-5a28dd985e47)

**Comment by mishba-ai** [comment]
I want to work on this , can you assign me this?

**Comment by zeitgeistxx** [comment]
@Debaditya-Som yeah fix this.

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som yeah fix this.

Okay I'm on it

**Comment by VineeTagarwaL-code** [comment]
Sending a pr request right now

**Comment by VineeTagarwaL-code** [comment]
> @Debaditya-Som yeah fix this.

I have sent a PR solving the above mentioned issue , thank you
