### ISSUE TITLE
Update on the Resources Pages

### ISSUE THREAD

**Issue by Sumit-creator** [Resourcio-Community/Resourcio_Community-Website#36]
I would love to improve the resources page of this website in terms of Navbar, Card Redesign, Margin, Spacing, etc. I have went through the website and found number of design errors

Navbar is not there
Footer is not there
Card design are not elegant, etc.

![Screenshot (360)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/63730957/b2aeaf6b-718e-4128-914f-f82a45c24936)

Allow me to work under GSSOC'23

**Comment by Avinash905** [comment]
I would like to work on this issue under GSSOC'23

**Comment by zeitgeistxx** [comment]
already it is assigned to somebody else
