### ISSUE TITLE
Modifications in the 'contact us' section

### ISSUE THREAD

**Issue by Ashna56** [Resourcio-Community/Resourcio_Community-Website#37]
Instead of the view profile buttons, I would add the icons to the various socials of the people mentioned in this section, below their photos.
By doing this, the page will look more tidy and minimalistic too. 
I would like to work on this issue under GSSOC'23.

**Comment by Pragati-3003** [comment]
I would like to contribute in this. 
So, please assign this issue to me to change it under Gssoc'23.

**Comment by Sathvik902** [comment]
@r3yc0n1c @ronitblenz @Abhirup-02 I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by zeitgeistxx** [comment]
Not required now.
