### ISSUE TITLE
Changing the footer styling

### ISSUE THREAD

**Issue by Vanshitgupta9717** [Resourcio-Community/Resourcio_Community-Website#40]
As a GSSOC' 23 contributor, I would like to change the designing of the footer style as it looks so boring  . Please assign this issue to me.

**Comment by mahekkg** [comment]
Hey @Abhirup-02 @Soumyajit2825 @ronitblenz 
Improving the footer to the application can provide various benefits for functionality and user experience. Consider including navigation links, social media icons, copyright information, terms of service, privacy policy, and contact information. These elements enhance navigation, brand visibility, legal compliance, and user trust. Customize the footer based on your application's goals and target audience will be beneficial.

I have already contributed to similar task which makes it easier to successfully complete the task
Please assign me this task under GSSoC'23
Thank you

**Comment by ghost** [comment]
hello sir can you assign this task to me I would like to make this footer more attractive it will be my pleasure if i work on it

**Comment by Soumyajit2825** [comment]
Project Admin will assign you if possible
No need to hurry
Thank You

**Comment by Peacesandy** [comment]
Please assign me this issue as GSSOC 23

**Comment by zeitgeistxx** [comment]
Already assigned to somebody else.
