### ISSUE TITLE
[BUG] No validations in Signup and Login Page

### ISSUE THREAD

**Issue by raghavawasthi24** [Resourcio-Community/Resourcio_Community-Website#41]
![Screenshot (102)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/113261155/bf131403-0f93-4bdd-9ac6-93a2a08a732d)

In the above image, it is accepting this entry which is completely invalid. So, I request you to assign me this issue.

How I will Fix?
I will add validations in form through Javascript which will accept only valid entries.

**Comment by Uj293** [comment]
Also there is no popup message on successful signup or signin. we can just add a alert message or a popup message on the top on successful signup ..
you can assign this issue to me under the GSSOC 2023.

**Comment by zeitgeistxx** [comment]
It's fixed now, but not deployed in production.
