### ISSUE TITLE
Catagory Section Cards

### ISSUE THREAD

**Issue by mahekkg** [Resourcio-Community/Resourcio_Community-Website#42]
Hello
I would like to improve the cards under categories section (online resource for remote learning). The size of the cards can be improved according to different views. 
![Screenshot (355)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/85817366/d046eb0e-507d-4bc7-8e48-b161db71887a)
![Screenshot (356)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/85817366/4bee018c-56d2-4507-9cfe-5e12ad3555c4)

Kindly assign me this task, and I will start working on it promptly.

Thank you!

**Comment by mahekkg** [comment]
Heyy
Please Review

**Comment by zeitgeistxx** [comment]
It has been fixed.
