### ISSUE TITLE
Backend issue

### ISSUE THREAD

**Issue by Uj293** [Resourcio-Community/Resourcio_Community-Website#43]
sign up and sign in is not working properly this is because you might not added any backend to the project , assign this issue to me under GSSOC 2023
how to solve?
I can add jwt authentication whenever a user logged in and store that data base on AWS using mongodb atlas i have done this before with my Task App so i have experience on this. you can assign this to me .

**Comment by zeitgeistxx** [comment]
You have to add backend API url in .env fie which I think you have missed out and we have JWT authentication placed in place.

**Comment by Uj293** [comment]
okk thanks
