### ISSUE TITLE
Footer: Copyright year needs to dynamic

### ISSUE THREAD

**Issue by urzahmed** [Resourcio-Community/Resourcio_Community-Website#44]
Hello Project Maintainer,
I hope you're well. I am impressed by your project and ideas.
There is a fault in copyright year it needs to be dynamic. I have already solved this issue.
Please assign me this issue under gssoc'2023.
I will be happy to contribute in your project.

**Comment by zeitgeistxx** [comment]
Thanks for point out the issue, as soon as we get the tags I will assign

**Comment by zeitgeistxx** [comment]
@urz-ahmed you have been assigned.
