### ISSUE TITLE
Adding Automatic Number Counter  widget to  the website 

### ISSUE THREAD

**Issue by abhi03ruchi** [Resourcio-Community/Resourcio_Community-Website#45]
<img width="1267" alt="Screenshot 2023-05-21 at 5 03 49 PM" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/105661636/09e3ce23-3c2c-4d15-9f19-d6a88338241a">

I would like to add an automatic number counter feature to this section of the website. This will enhance user experience.  It will add an element of dynamism and interaction that can make the website more compelling and memorable to visitors.

Please assign this task to me. I know HTML, CSS and javascript. And I am currently working on React js.

**Comment by zeitgeistxx** [comment]
When we get the issue tags, I will let you know. So keep an eye out

**Comment by abhi03ruchi** [comment]
ok

**Comment by abhi03ruchi** [comment]
Please assign this issue to me under Gssoc'23.

**Comment by Soumyajit2825** [comment]
> Please assign this issue to me under Gssoc'23.

Wait until the tags are provided 
We will assign you soon

**Comment by zeitgeistxx** [comment]
@abhi03ruchi start working. Sync your branch with our GSSOC23 branch.

**Comment by abhi03ruchi** [comment]
Hi, @Abhirup-02, I have resolved issue #45  and raised a pr. Please review and merge it.

**Comment by zeitgeistxx** [comment]
Your contribution is appreciated.
