### ISSUE TITLE
Navbar on every page [GSSOC'23]

### ISSUE THREAD

**Issue by jayasree-g** [Resourcio-Community/Resourcio_Community-Website#49]
Navbar can be consistently displayed on all pages of the website, including the inside pages. This will greatly improve the user experience by allowing easy navigation between different sections of the website.

I would like to work on **Routing** under GSSOC'23, kindly assign me this issue

**Comment by Parsanta** [comment]
can you please assign this to me under the label of gssoc23, so that I can start working on this routing

**Comment by Avinash905** [comment]
I would like to work on this issue under GSSOC'23

**Comment by Avinash905** [comment]
I would like to work on this issue under GSSOC'23

**Comment by nayan911** [comment]
Hello, can u please assign this issue to me under GSSOC'23.

**Comment by utkarshsingx** [comment]
**Subject**: Contribution Proposal: Implementing a Consistent Navbar Across All Pages

Hello Resourcio-Community,

I would like to contribute to your open-source project under GSSOC'23 by implementing a consistent navbar on every page of the website. I believe this enhancement will improve user experience and ease navigation. I am confident in my web development skills and attention to detail, and I am eager to collaborate with the project team to deliver a robust solution.

Thank you for considering my proposal.

Best regards,
**Utkarsh**

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23

**Comment by zeitgeistxx** [comment]
Not needed.
