### ISSUE TITLE
Size Hover effect on Cards of resourse section and about us section [GSSoc23']

### ISSUE THREAD

**Issue by LLawlite** [Resourcio-Community/Resourcio_Community-Website#50]
I will Add a Hover effect in which Hover the size of cards in the resources section and  in the about section  this will make it more interactive
Assign me this under [GSSoc23']

**Comment by Avinash905** [comment]
I would like to work on this issue under GSSOC'23

**Comment by zeitgeistxx** [comment]
No more work on the cards is required.
