### ISSUE TITLE
feat: automatic mailing system

### ISSUE THREAD

**Issue by SINJINI-G** [Resourcio-Community/Resourcio_Community-Website#51]
I can make a mailing system that will send mails on new user signup automatically.

Please assign this to me for gssoc..
@Abhirup-02 @r3yc0n1c @ronitblenz

**Comment by zeitgeistxx** [comment]
I have already setup the backend for this, you can use that API to implement it in frontend.

**Comment by zeitgeistxx** [comment]
@SINJINI-G  make new PR for this

**Comment by SINJINI-G** [comment]
> @SINJINI-G make new PR for this

Kindly check the new PR.
