### ISSUE TITLE
feat: Create Team component

### ISSUE THREAD

**Issue by SINJINI-G** [Resourcio-Community/Resourcio_Community-Website#52]
I will create a Team component which will contain all the team member profile cards in a sliding format.

Can you assign this issue to me for gssoc?
@Abhirup-02

**Comment by zeitgeistxx** [comment]
@SINJINI-G  great idea. Work on that component but don't make any PRs until the tags are added.

**Comment by SINJINI-G** [comment]
New PR have been done. Kindly review. @Abhirup-02
