### ISSUE TITLE
Request to Add Issue Templates: Bug Report, Feature Request, and Styling

### ISSUE THREAD

**Issue by mhdamaan79** [Resourcio-Community/Resourcio_Community-Website#55]
I suggest adding three essential templates to our project: **Bug Report, Feature Request, and Styling.**
These templates will improve project management and collaboration by offering standardized formats for reporting bugs, submitting feature requests, and addressing styling issues. They will streamline communication, enhance issue tracking, and ensure consistency in our development and design processes.

I would like to work on this issue under the **GSSoC'23.**  @Abhirup-02

**Comment by Soumyajit2825** [comment]
@Abhirup-02 have a look

**Comment by mhdamaan79** [comment]
Thank you for the assignment! I'm excited to contribute and will start working on the issue templates one by one from tomorrow. Kindly add the **GSSOC'23** label to this issue, please. @Abhirup-02

**Comment by mhdamaan79** [comment]
I've raised PRs for all **three templates.** Kindly review them. Your attention is greatly appreciated. Thank you! @Abhirup-02
