### ISSUE TITLE
Improve Responsiveness by resizing the content

### ISSUE THREAD

**Issue by Jiya-garg9971** [Resourcio-Community/Resourcio_Community-Website#57]
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/100217150/dea026e8-a272-4333-8578-11bf9f36ee67)

The size of content should be reduced in case of mobile view so that the user does not need to score too much.

**Comment by zeitgeistxx** [comment]
That's a good issue, you picked up @Jiya-garg9971

**Comment by zeitgeistxx** [comment]
@Jiya-garg9971 you haven't made any PR to our repo. Please click 'commits ahead' in your repo and then create a Pull Request
