### ISSUE TITLE
Resources Card UI Design

### ISSUE THREAD

**Issue by SONA-1111** [Resourcio-Community/Resourcio_Community-Website#58]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.
![card](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/114572821/31bb700c-0a60-4ddd-988e-3b523ede2646)

**Comment by zeitgeistxx** [comment]
Not needed as of now.
