### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by SONA-1111** [Resourcio-Community/Resourcio_Community-Website#59]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.

**Comment by Sandeep0306** [comment]
Hii, I want to add sticky navbar so it will looks more better .Please assign me this issue Under Gssoc'23.

**Comment by zeitgeistxx** [comment]
Someone have been assigned already.
