### ISSUE TITLE
Feature : Add count-up to the stats 

### ISSUE THREAD

**Issue by An525ish** [Resourcio-Community/Resourcio_Community-Website#62]
![reso](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/93612051/3d7e8cd4-61f4-46c3-945b-dccdd4a4ad64)

-- I want to add count-up to the stats here which will slowly increase the count of each stats in an animated manner

**Comment by utkarshsingx** [comment]
### **Subject:** Contribution Proposal: Adding Count-Up Animation to Website Stats

Hello **Resourcio-Community**,

I would like to contribute to your open-source project for GSSoC'23 by adding a count-up animation to the website's stats. This feature will enhance user engagement and provide an interactive experience. I am confident in my web development skills and eager to collaborate on this task.

Thank you for considering my proposal.

Best regards,
**Utkarsh**

**Comment by zeitgeistxx** [comment]
It is already assigned.
