### ISSUE TITLE
A new page for resources 

### ISSUE THREAD

**Issue by Palakkgoyal** [Resourcio-Community/Resourcio_Community-Website#63]
If we click on any resources button then it take us to the GitHub repo which is ok but I think if there will be special page on which all the resources are mention in a nice interface it will be more good
![Screenshot 2023-05-22 143512](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/116902573/1a99da70-f113-49b5-94a9-1c8b3f871e30)
![Screenshot 2023-05-22 143546](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/116902573/f505cd65-bc5f-4720-93c3-999e48bc31a7)

**Comment by zeitgeistxx** [comment]
The idea is good, but it is too much too handle for all the resources

**Comment by Palakkgoyal** [comment]
These are just text and links. We can do this by adding all this data to the backend and then do dynamic routing while fetching data or you are saying something else?

**Comment by zeitgeistxx** [comment]
Yeah I thought about that, but it is too much data to handle in the backend and the process will be elaborated. 
Adding them in repos is easy and if anyone wants to contribute in them, handling it would be easy too.

**Comment by Palakkgoyal** [comment]
If you agree can I work on it? Yes, in repos it would be easy.

**Comment by zeitgeistxx** [comment]
Then you have to wait, until my endsem exams are finished. Then I can properly coordinate with you.

**Comment by Palakkgoyal** [comment]
Sure

**Comment by Palakkgoyal** [comment]
Hey @Abhirup-02 Would you like to discuss about it now?

**Comment by Palakkgoyal** [comment]
Forgot to tell I am also a GSSOC contributer.

**Comment by zeitgeistxx** [comment]
@Palakkgoyal  Contributing in those Repos would not count, they are not registered under GSSOC

**Comment by Palakkgoyal** [comment]
It is mentioned. Watch this
![Screenshot 2023-06-10 213524](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/116902573/bdfaefa7-39b3-48a6-9454-dc8ffe3fca96)

**Comment by zeitgeistxx** [comment]
@Palakkgoyal  it is saying the only the Website Repo comes under consideration. Not the other ones

**Comment by Palakkgoyal** [comment]
Yes, I understand. But I apologize I am not able to understand which repos are you referring to that do not come under GSSOC. Can you please elaborate?

**Comment by zeitgeistxx** [comment]
First tell me on what exactly, do you want to work?

**Comment by Palakkgoyal** [comment]
Yes, I want to work on it.

**Comment by zeitgeistxx** [comment]
> Yes, I want to work on it.

Not like that, tell me on what you want to work exactly

**Comment by Palakkgoyal** [comment]
When we click on Learn More on the Resources page then, it leads us to GitHub. So, I want to make a new page that will demonstrate all the resources in a better way instead of just leading us to GitHub.

**Comment by zeitgeistxx** [comment]
Then we have register for Github Apps.....I still want to store all the resources in Github
