### ISSUE TITLE
Improve the UI Experience of Get In Touch Card 

### ISSUE THREAD

**Issue by Preetam078** [Resourcio-Community/Resourcio_Community-Website#67]
I want to add some hover zooming effect and some box shabow to the Card in Get in Touch Card component to make the UI Experience  more enhanced.
![Screenshot from 2023-05-22 21-48-54](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/81969353/429a1f70-376a-4244-89e0-32d73adac591)

please assign this task to me under the GSSoC 2023

**Comment by Preetam078** [comment]
Hi Admin please assign this task to me under the GSSoC 23

**Comment by zeitgeistxx** [comment]
Not needed.
