### ISSUE TITLE
[FEATURE] Adding Dark mode to the whole Website 

### ISSUE THREAD

**Issue by Preetam078** [Resourcio-Community/Resourcio_Community-Website#68]
Hi  Team I have observed that the UI of the Project is Good but I can add a feature of Dark mode by adding a attractive button on the Navbar and by using Context API to switch between Light mode and Dark mode. 
![Screenshot from 2023-05-22 21-58-52](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/81969353/824ba81a-06f9-4320-bf35-0411416a9c43)

please Assign this task to me under the GSSoC 23

**Comment by Preetam078** [comment]
hi  admin please assign this task to me under the GSSoC 23

**Comment by zeitgeistxx** [comment]
It has already been assigned to somebody else
