### ISSUE TITLE
Rewriting Readme.md

### ISSUE THREAD

**Issue by Atharva-3000** [Resourcio-Community/Resourcio_Community-Website#7]
The Readme file is incomplete.
**Can I make a new** readme to be shown with all the details?
(For GSSOC23)

**Comment by pritish0666** [comment]
Hi. assign it to me. I will rewrite the ReadMe file within 2 days.

**Comment by manasi-jain** [comment]
Hi, I'm interested in working on this issue. Can I contribute to its resolution?

**Comment by Atharva-3000** [comment]
@pritish0666 @manasi-jain, I myself am a contributor, who has raised the issue as I saw fit 😅 .

**Comment by zeitgeistxx** [comment]
So I have provided README.md 
I just want another improvement, which will kind of look like this is README.md


![WhatsApp Image 2023-05-20 at 22 07 10](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/92736753/e16e2956-f59d-4c43-b80b-3e1fc0ed9be8)

**Comment by Atharva-3000** [comment]
@Abhirup-02 ok I'll add a table of content to the current README according to the points mentioned in the readme present right now.
Working on it.

**Comment by zeitgeistxx** [comment]
I showed you the demo, we don't have exactly these sections in RADME. So look at the sections and add them in content table accordingly. @Atharva-3000

**Comment by Atharva-3000** [comment]
> I showed you the demo, we don't have exactly these sections in RADME. So look at the sections and add them in content table accordingly. @Atharva-3000 
> 

Already working on it 👍🏼
