### ISSUE TITLE
To change the styles and hover effect of buttons under Contact Us section to a different layout

### ISSUE THREAD

**Issue by Sahdev-rajput** [Resourcio-Community/Resourcio_Community-Website#70]
I want to enhance the styles of buttons  and to enhance the button layout on hovering to by adding attractive styles.
![Screenshot (10)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/108891970/20a01a1f-959a-4313-9bb8-1d9f7c9c37c8)
Please assign my issue.
Thanks

**Comment by zeitgeistxx** [comment]
Not required.
