### ISSUE TITLE
Uneven Card heights in Resources Section [GSSOC'23]

### ISSUE THREAD

**Issue by vishnu9865** [Resourcio-Community/Resourcio_Community-Website#8]
![image](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/91585213/dd2ce752-5e09-4983-81b9-c64bc57ff07b)

The cards in Resource Section of the website is uneven and feels tacky but the solution is fairly available. @GSSOC'23
Can you please assign this issue to me ?
Thank you.

**Comment by vishnu9865** [comment]
@Abhirup-02 Can you please assign this issue to me. Thanks in Advance.

**Comment by AMAN-J-B** [comment]
> Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
> I will try to make it as different as possible and exciting also.
> Please assign it to me. Thank you in advance.😇

**Comment by zeitgeistxx** [comment]
@vishnu9865 you can work on that

**Comment by vishnu9865** [comment]
@Abhirup-02 Thank you for assigning me. 👍🏽😊
