### ISSUE TITLE
Improve index.js file code 

### ISSUE THREAD

**Issue by blessingblockchain** [Resourcio-Community/Resourcio_Community-Website#82]
(1) Use ReactDOM.render instead of ReactDOM.createRoot: The code currently uses the experimental createRoot API from ReactDOM. Unless you specifically require the additional features provided by createRoot, it's recommended to use the standard ReactDOM.render method instead.

(2) Wrap the application with the necessary context providers: It appears that the code is using an AuthContextProvider from the AuthContext module. You can wrap the <App /> component with the AuthContextProvider to provide the necessary authentication context to the application.

(3) Import only the necessary modules: The code currently imports the ReactDOM module from react-dom/client, which is not necessary. You can import ReactDOM directly from 'react-dom' instead.

Assign me this issue @r3yc0n1c so i can raise a Pr

**Comment by zeitgeistxx** [comment]
@blessingblockchain I get it, what you are suggesting, but I don't think point no. 2 is needed.

**Comment by blessingblockchain** [comment]
oh if you feel no 2 isnt needed, its cool.

but can i raise Pr for the rest issues, im suggesting you assign me so i could make changes to improve the code ? Then you can see @Abhirup-02

**Comment by aditya8218769976** [comment]
Can I also work on this

**Comment by zeitgeistxx** [comment]
hey @blessingblockchain what's your status?

**Comment by Abhinavcode13** [comment]
@Abhirup-02 what's update on this?

**Comment by blessingblockchain** [comment]
Sorry man @Abhirup-02 I would complete it today

**Comment by agarwalhimanshugaya** [comment]
i also want to work on this can you give me a chance

**Comment by zeitgeistxx** [comment]
yes @agarwalhimanshugaya i am reassigning it to you
