### ISSUE TITLE
[FEATURE REQUEST] Add Hover animations to the cards

### ISSUE THREAD

**Issue by abhinav-m22** [Resourcio-Community/Resourcio_Community-Website#87]
Adding hover effects, animations on these cards of statistics will improve the UI/UX and maintain consistency throughout the website as other components also have the effects.

Image of the section:

<img width="933" alt="image" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/113239388/9d167c02-845d-43d2-b84f-a77470f5812e">

I want to work on the feature.
Please assign me the task under GSSoC'23.

**Comment by zeitgeistxx** [comment]
As there is nothing to interact with those cards. Hover effect on them is unnecessary.
