### ISSUE TITLE
[FEATURE REQUEST] : Adding Framer animation to all components

### ISSUE THREAD

**Issue by Tushar98644** [Resourcio-Community/Resourcio_Community-Website#88]
## Description

Right now the cards and buttons don't have any animation and look very plain, I would like to add animation to those using framer motion

**Comment by Tushar98644** [comment]
@Abhirup-02 i would like to take up this issue....

**Comment by zeitgeistxx** [comment]
@Tushar98644 try to keep it simple.

**Comment by harmeetsingh11** [comment]
If no one is working on this issue, can I work on this issue under GSSoC'23? @Abhirup-02

**Comment by zeitgeistxx** [comment]
@Tushar98644 are you working on this issue?

**Comment by zeitgeistxx** [comment]
Issue has been closed. No response from assignee.
