### ISSUE TITLE
[FEATURE REQUEST] : Google Sign In option

### ISSUE THREAD

**Issue by Tushar98644** [Resourcio-Community/Resourcio_Community-Website#89]
## Description

**Is your feature request related to a problem? Please describe.**

Right now there is only the option of sign up using username and password which can be frustrating for some users , I would like to add google sign up and sign in option

**Comment by Tushar98644** [comment]
@Soumyajit2825 @Abhirup-02 i would like to work on this issue ....

**Comment by zeitgeistxx** [comment]
Google sign in not required now.
