### ISSUE TITLE
Redesigning the navbar with proper spacing 

### ISSUE THREAD

**Issue by svandu** [Resourcio-Community/Resourcio_Community-Website#9]
![Screenshot 2023-05-20 012246](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/94906179/d15260f1-10b8-4be2-8858-93dc59cdd154)
Please assign me for this

**Comment by mahekkg** [comment]
Hello
The website is adopting a minimalist design approach, this helps achieve a cleaner and more streamlined navigation system.
The current navbar design could benefit from an update to align with website and proper spacing. 
Minimalist design focuses on simplicity, clarity, and removing unnecessary elements, resulting in a visually appealing and user-friendly interface.

I earlier worked on the similar task and have proper experience.
Please assign this task to me if you agree it will benefit our project under GSSoC'23. 

Thank you
Mahek Goswami

**Comment by Abhirup-02** [comment]
No more work on navbar currently required.
