### ISSUE TITLE
[BUG] : Dependancy error 

### ISSUE THREAD

**Issue by Tushar98644** [Resourcio-Community/Resourcio_Community-Website#91]
## Description

Upon installing the dependencies using `sudo npm install` , i am facing the following error (refer to the screenshot below):

<img width="1440" alt="Screenshot 2023-05-24 at 11 13 34 AM" src="https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/107763774/40ec0cf4-f13b-44bd-afa5-8968b797ba85">

**Comment by zeitgeistxx** [comment]
Let me check

**Comment by Tushar98644** [comment]
> Let me check

any updates

**Comment by Sumit-pd** [comment]
i think you need to use the latest version of node

**Comment by zeitgeistxx** [comment]
> i think you need to use the latest version of node

it shouldn't make any issue

**Comment by Tushar98644** [comment]
> i think you need to use the latest version of node

I am using node v 18
