### ISSUE TITLE
create a dynamic image slider in about  us section [FEATURE REQUEST] 

### ISSUE THREAD

**Issue by mandliyarajendra11** [Resourcio-Community/Resourcio_Community-Website#93]
## Description

**Is your feature request related to a problem? Please describe.**
in about us section past workshop image slider is not looking good.

**Describe the solution you'd like**
i can create autoplay image slider

![Screenshot (106)](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/119125519/4382e5dd-7235-439a-8ce5-cfcc88170184)

**Comment by zeitgeistxx** [comment]
Not required right now.
