### ISSUE TITLE
Want to add button to change the theme of the website[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by HimanshuNarware** [Resourcio-Community/Resourcio_Community-Website#96]
## Description

**Is your feature request related to a problem? Please describe.**
Want to add a button to change the theme of the website, it improve the UI of the website

**Describe the solution you'd like**
I want to add a button on the navbar to change the theme of the website from white to black

## Additional Information

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.
![2](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/83147410/e53969d1-4d51-44ff-9429-45fa354c1fbd)

*

**Comment by zeitgeistxx** [comment]
Already assigned to another contibutor.
