### ISSUE TITLE
Spelling  mistakes in the website [FEATURE REQUEST] 

### ISSUE THREAD

**Issue by HimanshuNarware** [Resourcio-Community/Resourcio_Community-Website#97]
## Description

**Is your feature request related to a problem? Please describe.**
Spelling mistakes in the website, It affecting the readability of the Website

**Describe the solution you'd like**
I want to resolve them, I have a very strong command over the language

## Additional Information

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

![3](https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/83147410/b8438c30-a48b-45e9-ab7b-3ddd378b8ffe)

**Comment by zeitgeistxx** [comment]
@HimanshuNarware get on with it.

**Comment by aditya8218769976** [comment]
Can you please which page is having spelling mistake

**Comment by HimanshuNarware** [comment]
> Can you please which page is having spelling mistake

in every page
